<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows8.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="Microsoft.SqlServer.Types" Version="14.0.1016.290" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0' or '$(TargetFramework)' == 'net9.0-windows8.0' or '$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Geometry\Geometry.csproj" />
    <ProjectReference Include="..\..\Clients\VolumeModel\VolumeModel.csproj" />
    <ProjectReference Include="..\..\Clients\WebAnnotationModel\WebAnnotationModel.csproj" />
    <ProjectReference Include="..\..\Clients\Common\Common.csproj" />
  </ItemGroup>
</Project>