<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>VolumeViewModel</AssemblyName>
    <RootNamespace>Viking.VolumeViewModel</RootNamespace>
    <UseWPF>true</UseWPF>
    <OutputPath Condition="'$(Configuration)' == 'Debug'">..\..\Jotunn\bin\Debug\Modules\VolumeViewModel\</OutputPath>
    <OutputPath Condition="'$(Configuration)' == 'Release'">..\..\Jotunn\bin\Release\Modules\VolumeViewModel\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Core" Version="6.2.0" />
    <PackageReference Include="Prism.Mef" Version="6.2.0" />
    <PackageReference Include="Prism.Wpf" Version="6.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Common.csproj" />
    <ProjectReference Include="..\..\..\Geometry\Geometry.csproj" />
    <ProjectReference Include="..\..\VolumeModel\VolumeModel.csproj" />
    <ProjectReference Include="..\JotunnCommon\JotunnUICommon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="app.config" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="mkdir &quot;$(SolutionDir)Jotunn\Jotunn\Modules\$(TargetName)&quot;&#xD;&#xA;copy $(TargetDir)\*.dll &quot;$(SolutionDir)Jotunn\Jotunn\Modules\$(TargetName)&quot;&#xD;&#xA;copy $(TargetDir)\*.pdb &quot;$(SolutionDir)Jotunn\Jotunn\Modules\$(TargetName)&quot;" />
  </Target>

</Project>
