<?xml version="1.0" encoding="utf-8"?>
<Database Name="New" EntityNamespace="Tracker.Model" ContextNamespace="Tracker" Class="DB" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=&quot;C:\Program Files (x86)\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\New.mdf&quot;;Integrated Security=True;Connect Timeout=30;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NewConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DeletedLocations" Member="DeletedLocations">
    <Type Name="DeletedLocation">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Location" Member="Locations">
    <Type Name="Location">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="X" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Y" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Z" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Verticies" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" />
      <Column Name="Closed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="Overlay" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" />
      <Column Name="Tags" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="VolumeX" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="VolumeY" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Terminal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OffEdge" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Radius" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TypeCode" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Location_LocationLink" Member="LocationLinks" ThisKey="ID" OtherKey="A" Type="LocationLink" />
      <Association Name="Location_LocationLink1" Member="LocationLinks1" ThisKey="ID" OtherKey="B" Type="LocationLink" />
      <Association Name="Structure_Location" Member="Structure" ThisKey="ParentID" OtherKey="ID" Type="Structure" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LocationLink" Member="LocationLinks">
    <Type Name="LocationLink">
      <Column Name="A" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="B" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Location_LocationLink" Member="Location" ThisKey="A" OtherKey="ID" Type="Location" IsForeignKey="true" />
      <Association Name="Location_LocationLink1" Member="Location1" ThisKey="B" OtherKey="ID" Type="Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Structure" Member="Structures">
    <Type Name="Structure">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="Verified" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Tags" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="Confidence" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="ParentID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Association Name="Structure_Location" Member="Locations" ThisKey="ID" OtherKey="ParentID" Type="Location" />
      <Association Name="Structure_Structure" Member="Structures" ThisKey="ID" OtherKey="ParentID" Type="Structure" />
      <Association Name="Structure_StructureLink" Member="StructureLinks" ThisKey="ID" OtherKey="SourceID" Type="StructureLink" />
      <Association Name="Structure_StructureLink1" Member="StructureLinks1" ThisKey="ID" OtherKey="TargetID" Type="StructureLink" />
      <Association Name="Structure_Structure" Member="Structure1" ThisKey="ParentID" OtherKey="ID" Type="Structure" IsForeignKey="true" />
      <Association Name="StructureType_Structure" Member="StructureType" ThisKey="TypeID" OtherKey="ID" Type="StructureType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StructureLink" Member="StructureLinks">
    <Type Name="StructureLink">
      <Column Name="SourceID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TargetID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Bidirectional" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Structure_StructureLink" Member="Structure" ThisKey="SourceID" OtherKey="ID" Type="Structure" IsForeignKey="true" />
      <Association Name="Structure_StructureLink1" Member="Structure1" ThisKey="TargetID" OtherKey="ID" Type="Structure" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StructureTemplates" Member="StructureTemplates">
    <Type Name="StructureTemplate">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="Char(64) NOT NULL" CanBeNull="false" />
      <Column Name="StructureTypeID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="StructureTags" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="StructureType_StructureTemplate" Member="StructureType" ThisKey="StructureTypeID" OtherKey="ID" Type="StructureType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StructureType" Member="StructureTypes">
    <Type Name="StructureType">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="MarkupType" Type="System.String" DbType="NChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Tags" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="StructureTags" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="Abstract" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="Code" Type="System.String" DbType="NChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="HotKey" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Association Name="StructureType_Structure" Member="Structures" ThisKey="ID" OtherKey="TypeID" Type="Structure" />
      <Association Name="StructureType_StructureTemplate" Member="StructureTemplates" ThisKey="ID" OtherKey="StructureTypeID" Type="StructureTemplate" />
      <Association Name="StructureType_StructureType" Member="StructureTypes" ThisKey="ID" OtherKey="ParentID" Type="StructureType" />
      <Association Name="StructureType_StructureType" Member="StructureType1" ThisKey="ParentID" OtherKey="ID" Type="StructureType" IsForeignKey="true" />
    </Type>
  </Table>
</Database>