<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <UseWPF>false</UseWPF>
    <UseWindowsForms>false</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="EntityFrameworkExtras.EF6" Version="3.0.5" />
    <PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="Microsoft.SqlServer.Types" Version="14.0.1016.290" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Libs/EntityFrameworkExtras/EntityFrameworkExtras.EF6/EntityFrameworkExtras.EF6.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EntityDeploy Include="ConnectomeDataModel.edmx">
      <Generator>EntityModelCodeGenerator</Generator>
      <LastGenOutput>ConnectomeDataModel.Designer.cs</LastGenOutput>
    </EntityDeploy>
    <None Include="DataModel.Context.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <DependentUpon>ConnectomeDataModel.edmx</DependentUpon>
      <LastGenOutput>DataModel.Context.cs</LastGenOutput>
    </None>
    <None Include="ConnectomeDataModel.edmx.diagram">
      <DependentUpon>ConnectomeDataModel.edmx</DependentUpon>
    </None>
    <None Include="DataModel.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <DependentUpon>ConnectomeDataModel.edmx</DependentUpon>
      <LastGenOutput>DataModel.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349B6-6B84-4DF5-91F0-309BEEBAD82D}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="ConnectomeDataModel.Context.cs" />
    <Compile Remove="ConnectomeDataModel.Designer.cs" />
  </ItemGroup>

</Project>