# BuildKit uses this file instead of the repo-root .dockerignore.

**

!Directory.Build.props
!gRPC_Protos/SectionCorrection/
!gRPC_Protos/SectionCorrection/**
!SectionCorrectionServiceTypes.gRPC/
!SectionCorrectionServiceTypes.gRPC/**
!Servers/GrpcSectionCorrectionService/
!Servers/GrpcSectionCorrectionService/**
!Servers/SectionCorrection/
!Servers/SectionCorrection/**
!Servers/SectionCorrectionBuilder/
!Servers/SectionCorrectionBuilder/**
!Servers/ConnectomeDataModelCore/
!Servers/ConnectomeDataModelCore/**
!AnnotationVizLib/
!AnnotationVizLib/**
!AnnotationInterfaces/
!AnnotationInterfaces/**
!Clients/VolumeModel/
!Clients/VolumeModel/**
!Clients/Common/
!Clients/Common/**
!Geometry/
!Geometry/**
!Geometry.Core/
!Geometry.Core/**
!GraphLib/
!GraphLib/**
!RTree/
!RTree/**
!Utils/
!Utils/**
!UnitsAndScale/
!UnitsAndScale/**
!SqlGeometryUtils/
!SqlGeometryUtils/**
!Triangle.NET/Triangle/
!Triangle.NET/Triangle/**

**/bin/
**/bin/**
**/obj/
**/obj/**
