<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Viking.VolumeView</RootNamespace>
    <AssemblyName>VolumeView</AssemblyName>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JotunnCommon\JotunnUICommon.csproj" />
    <ProjectReference Include="..\JotunnUIControls\JotunnUIControls.csproj" />
    <ProjectReference Include="..\VolumeViewModel\VolumeViewModel.csproj" />
    <ProjectReference Include="..\..\Viking.Scene\Viking.Scene.csproj" />
    <ProjectReference Include="..\..\Viking.Input\Viking.Input.csproj" />
    <ProjectReference Include="..\..\Viking\WebAnnotation\WebAnnotation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="VikingVolumeViewModule.cs" />
    <Compile Remove="Test.cs" />
    <Compile Remove="Properties\Settings.Designer.cs" />
    <Compile Remove="Properties\Resources.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Point.bmp" />
  </ItemGroup>

</Project>
