<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AnnotationVizLib\AnnotationVizLib.csproj" />
    <ProjectReference Include="..\Geometry\Geometry.csproj" />
    <ProjectReference Include="..\SqlGeometryUtils\SqlGeometryUtils.csproj" />
  </ItemGroup>
</Project>