<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MorphologyMesh\MorphologyMesh.csproj" />
    <ProjectReference Include="..\UnitsAndScale\UnitsAndScale.csproj" />
  </ItemGroup>
</Project>