//
// This code was generated by Visual ReCode 2.0.3.1140
//

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;
using Grpc.Core;
#if(NETSTANDARD2_1)
using Grpc.Net.Client;
#endif

namespace gRPCAnnotationServiceCore.Client
{
    public partial class AnnotateLocationsClient : IAnnotateLocationsClient, IDisposable
    {
        private readonly gRPCAnnotationServiceCore.Client.Protos.AnnotateLocations.AnnotateLocationsClient _client;
        
        public AnnotateLocationsClient(gRPCAnnotationServiceCore.Client.Protos.AnnotateLocations.AnnotateLocationsClient client)
        {
            _client = client;
        }
        
#if(NETSTANDARD2_1)
        private readonly GrpcChannel _channel;

        public AnnotateLocationsClient(string url)
        {
            _channel = GrpcChannel.ForAddress(url);
            _client = new gRPCAnnotationServiceCore.Client.Protos.AnnotateLocations.AnnotateLocationsClient(_channel);
        }

        public void Dispose()
        {
            _channel?.Dispose();
        }
#else
        private readonly Channel _channel;

        public AnnotateLocationsClient(string url)
        {
            var uri = new Uri(url);
            _channel = new Channel(uri.Host, uri.Port, ChannelCredentials.Insecure);
            _client = new gRPCAnnotationServiceCore.Client.Protos.AnnotateLocations.AnnotateLocationsClient(_channel);
        }

        public void Dispose()
        {
            if (_channel is null) return;
            try
            {
                _channel.ShutdownAsync().GetAwaiter().GetResult();
            }
            catch
            {
                // Ignored
            }
        }
#endif

        public async Task<Location> CreateLocationAsync(Location obj, long[] LinkedIDs)
        {
            var request = new Protos.CreateLocationRequest
            {
                Obj = (Protos.Location)obj,
            };
            request.LinkedIds.AddRange(LinkedIDs);
            var response = await _client.CreateLocationAsync(request);
            var returnValue = (global::gRPCAnnotationServiceCore.Client.Location)response.Value;
            return returnValue;
        }

        [Obsolete("Use CreateLocationAsync")]
        public Location CreateLocation(Location obj, long[] LinkedIDs)
        {
            return CreateLocationAsync(obj, LinkedIDs).GetAwaiter().GetResult();
        }
        
        public async Task<Location> GetLocationByIDAsync(long ID)
        {
            var request = new Protos.GetLocationByIDRequest
            {
                Id = ID,
            };
            var response = await _client.GetLocationByIDAsync(request);
            var returnValue = (global::gRPCAnnotationServiceCore.Client.Location)response.Value;
            return returnValue;
        }

        [Obsolete("Use GetLocationByIDAsync")]
        public Location GetLocationByID(long ID)
        {
            return GetLocationByIDAsync(ID).GetAwaiter().GetResult();
        }
        
        public async Task<Location[]> GetLocationsByIDAsync(long[] IDs)
        {
            var request = new Protos.GetLocationsByIDRequest();
            request.Ids.AddRange(IDs);
            var response = await _client.GetLocationsByIDAsync(request);
            var returnValue = response.Values.Select(x => (global::gRPCAnnotationServiceCore.Client.Location)x).ToArray();
            return returnValue;
        }

        [Obsolete("Use GetLocationsByIDAsync")]
        public Location[] GetLocationsByID(long[] IDs)
        {
            return GetLocationsByIDAsync(IDs).GetAwaiter().GetResult();
        }
        
        public async Task<Location> GetLastModifiedLocationAsync()
        {
            var request = new Protos.GetLastModifiedLocationRequest();
            var response = await _client.GetLastModifiedLocationAsync(request);
            var returnValue = (global::gRPCAnnotationServiceCore.Client.Location)response.Value;
            return returnValue;
        }

        [Obsolete("Use GetLastModifiedLocationAsync")]
        public Location GetLastModifiedLocation()
        {
            return GetLastModifiedLocationAsync().GetAwaiter().GetResult();
        }
        
        public async Task<long[]> GetLinkedLocationsAsync(long ID)
        {
            var request = new Protos.GetLinkedLocationsRequest
            {
                Id = ID,
            };
            var response = await _client.GetLinkedLocationsAsync(request);
            var returnValue = response.Values.ToArray();
            return returnValue;
        }

        [Obsolete("Use GetLinkedLocationsAsync")]
        public long[] GetLinkedLocations(long ID)
        {
            return GetLinkedLocationsAsync(ID).GetAwaiter().GetResult();
        }
        
        public async Task<Location[]> GetLocationsForSectionAsync(long section, long QueryExecutedTime)
        {
            var request = new Protos.GetLocationsForSectionRequest
            {
                Section = section,
                QueryExecutedTime = QueryExecutedTime,
            };
            var response = await _client.GetLocationsForSectionAsync(request);
            var returnValue = response.Values.Select(x => (global::gRPCAnnotationServiceCore.Client.Location)x).ToArray();
            return returnValue;
        }

        [Obsolete("Use GetLocationsForSectionAsync")]
        public Location[] GetLocationsForSection(long section, long QueryExecutedTime)
        {
            return GetLocationsForSectionAsync(section, QueryExecutedTime).GetAwaiter().GetResult();
        }
        
        public async Task<Location[]> GetLocationsForStructureAsync(long structureID)
        {
            var request = new Protos.GetLocationsForStructureRequest
            {
                StructureId = structureID,
            };
            var response = await _client.GetLocationsForStructureAsync(request);
            var returnValue = response.Values.Select(x => (global::gRPCAnnotationServiceCore.Client.Location)x).ToArray();
            return returnValue;
        }

        [Obsolete("Use GetLocationsForStructureAsync")]
        public Location[] GetLocationsForStructure(long structureID)
        {
            return GetLocationsForStructureAsync(structureID).GetAwaiter().GetResult();
        }
        
        public async Task<Location[]> GetLocationChangesInMosaicRegionAsync(long section, BoundingRectangle bbox, double MinRadius, long? ModifiedAfterThisUtcTime, long QueryExecutedTime, long[] DeletedIDs)
        {
            var request = new Protos.GetLocationChangesInMosaicRegionRequest
            {
                Section = section,
                Bbox = (Protos.BoundingRectangle)bbox,
                MinRadius = MinRadius,
                ModifiedAfterThisUtcTime = ModifiedAfterThisUtcTime,
                QueryExecutedTime = QueryExecutedTime,
            };
            request.DeletedIds.AddRange(DeletedIDs);
            var response = await _client.GetLocationChangesInMosaicRegionAsync(request);
            var returnValue = response.Values.Select(x => (global::gRPCAnnotationServiceCore.Client.Location)x).ToArray();
            return returnValue;
        }

        [Obsolete("Use GetLocationChangesInMosaicRegionAsync")]
        public Location[] GetLocationChangesInMosaicRegion(long section, BoundingRectangle bbox, double MinRadius, long? ModifiedAfterThisUtcTime, long QueryExecutedTime, long[] DeletedIDs)
        {
            return GetLocationChangesInMosaicRegionAsync(section, bbox, MinRadius, ModifiedAfterThisUtcTime, QueryExecutedTime, DeletedIDs).GetAwaiter().GetResult();
        }
        
        public async Task<AnnotationSet> GetAnnotationsInMosaicRegionAsync(long section, BoundingRectangle bbox, double MinRadius, long? ModifiedAfterThisUtcTime, long QueryExecutedTime, long[] DeletedIDs)
        {
            var request = new Protos.GetAnnotationsInMosaicRegionRequest
            {
                Section = section,
                Bbox = (Protos.BoundingRectangle)bbox,
                MinRadius = MinRadius,
                ModifiedAfterThisUtcTime = ModifiedAfterThisUtcTime,
                QueryExecutedTime = QueryExecutedTime,
            };
            request.DeletedIds.AddRange(DeletedIDs);
            var response = await _client.GetAnnotationsInMosaicRegionAsync(request);
            var returnValue = (global::gRPCAnnotationServiceCore.Client.AnnotationSet)response.Value;
            return returnValue;
        }

        [Obsolete("Use GetAnnotationsInMosaicRegionAsync")]
        public AnnotationSet GetAnnotationsInMosaicRegion(long section, BoundingRectangle bbox, double MinRadius, long? ModifiedAfterThisUtcTime, long QueryExecutedTime, long[] DeletedIDs)
        {
            return GetAnnotationsInMosaicRegionAsync(section, bbox, MinRadius, ModifiedAfterThisUtcTime, QueryExecutedTime, DeletedIDs).GetAwaiter().GetResult();
        }
        
        public async Task<Location[]> GetLocationChangesAsync(long section, long ModifiedAfterThisUtcTime, long QueryExecutedTime, long[] DeletedIDs)
        {
            var request = new Protos.GetLocationChangesRequest
            {
                Section = section,
                ModifiedAfterThisUtcTime = ModifiedAfterThisUtcTime,
                QueryExecutedTime = QueryExecutedTime,
            };
            request.DeletedIds.AddRange(DeletedIDs);
            var response = await _client.GetLocationChangesAsync(request);
            var returnValue = response.Values.Select(x => (global::gRPCAnnotationServiceCore.Client.Location)x).ToArray();
            return returnValue;
        }

        [Obsolete("Use GetLocationChangesAsync")]
        public Location[] GetLocationChanges(long section, long ModifiedAfterThisUtcTime, long QueryExecutedTime, long[] DeletedIDs)
        {
            return GetLocationChangesAsync(section, ModifiedAfterThisUtcTime, QueryExecutedTime, DeletedIDs).GetAwaiter().GetResult();
        }
        
        public async Task<long[]> UpdateAsync(Location[] locations)
        {
            var request = new Protos.UpdateRequest();
            request.Locations.AddRange(locations.Select(x => (Protos.Location)x));
            var response = await _client.UpdateAsync(request);
            var returnValue = response.Values.ToArray();
            return returnValue;
        }

        [Obsolete("Use UpdateAsync")]
        public long[] Update(Location[] locations)
        {
            return UpdateAsync(locations).GetAwaiter().GetResult();
        }
        
        public async Task CreateLocationLinkAsync(long SourceID, long TargetID)
        {
            var request = new Protos.CreateLocationLinkRequest
            {
                SourceId = SourceID,
                TargetId = TargetID,
            };
            await _client.CreateLocationLinkAsync(request);
        }

        [Obsolete("Use CreateLocationLinkAsync")]
        public void CreateLocationLink(long SourceID, long TargetID)
        {
            CreateLocationLinkAsync(SourceID, TargetID).GetAwaiter().GetResult();
        }
        
        public async Task DeleteLocationLinkAsync(long SourceID, long TargetID)
        {
            var request = new Protos.DeleteLocationLinkRequest
            {
                SourceId = SourceID,
                TargetId = TargetID,
            };
            await _client.DeleteLocationLinkAsync(request);
        }

        [Obsolete("Use DeleteLocationLinkAsync")]
        public void DeleteLocationLink(long SourceID, long TargetID)
        {
            DeleteLocationLinkAsync(SourceID, TargetID).GetAwaiter().GetResult();
        }
        
        public async Task<LocationLink[]> GetLocationLinksForSectionAsync(long section, long ModifiedAfterThisTime, long QueryExecutedTime, LocationLink[] DeletedLinks)
        {
            var request = new Protos.GetLocationLinksForSectionRequest
            {
                Section = section,
                ModifiedAfterThisTime = ModifiedAfterThisTime,
                QueryExecutedTime = QueryExecutedTime,
            };
            request.DeletedLinks.AddRange(DeletedLinks.Select(x => (Protos.LocationLink)x));
            var response = await _client.GetLocationLinksForSectionAsync(request);
            var returnValue = response.Values.Select(x => (global::gRPCAnnotationServiceCore.Client.LocationLink)x).ToArray();
            return returnValue;
        }

        [Obsolete("Use GetLocationLinksForSectionAsync")]
        public LocationLink[] GetLocationLinksForSection(long section, long ModifiedAfterThisTime, long QueryExecutedTime, LocationLink[] DeletedLinks)
        {
            return GetLocationLinksForSectionAsync(section, ModifiedAfterThisTime, QueryExecutedTime, DeletedLinks).GetAwaiter().GetResult();
        }
        
        public async Task<LocationLink[]> GetLocationLinksForSectionInMosaicRegionAsync(long section, BoundingRectangle bbox, double MinRadius, long ModifiedAfterThisUtcTime, long QueryExecutedTime, LocationLink[] DeletedLinks)
        {
            var request = new Protos.GetLocationLinksForSectionInMosaicRegionRequest
            {
                Section = section,
                Bbox = (Protos.BoundingRectangle)bbox,
                MinRadius = MinRadius,
                ModifiedAfterThisUtcTime = ModifiedAfterThisUtcTime,
                QueryExecutedTime = QueryExecutedTime,
            };
            request.DeletedLinks.AddRange(DeletedLinks.Select(x => (Protos.LocationLink)x));
            var response = await _client.GetLocationLinksForSectionInMosaicRegionAsync(request);
            var returnValue = response.Values.Select(x => (global::gRPCAnnotationServiceCore.Client.LocationLink)x).ToArray();
            return returnValue;
        }

        [Obsolete("Use GetLocationLinksForSectionInMosaicRegionAsync")]
        public LocationLink[] GetLocationLinksForSectionInMosaicRegion(long section, BoundingRectangle bbox, double MinRadius, long ModifiedAfterThisUtcTime, long QueryExecutedTime, LocationLink[] DeletedLinks)
        {
            return GetLocationLinksForSectionInMosaicRegionAsync(section, bbox, MinRadius, ModifiedAfterThisUtcTime, QueryExecutedTime, DeletedLinks).GetAwaiter().GetResult();
        }
        
        public async Task<LocationHistory[]> GetLocationChangeLogAsync(long? structure_id, DateTime? begin_time, DateTime? end_time)
        {
            var request = new Protos.GetLocationChangeLogRequest
            {
                StructureId = structure_id,
                BeginTime = begin_time.HasValue ? Timestamp.FromDateTime(begin_time.Value) : default,
                EndTime = end_time.HasValue ? Timestamp.FromDateTime(end_time.Value) : default,
            };
            var response = await _client.GetLocationChangeLogAsync(request);
            var returnValue = response.Values.Select(x => (global::gRPCAnnotationServiceCore.Client.LocationHistory)x).ToArray();
            return returnValue;
        }

        [Obsolete("Use GetLocationChangeLogAsync")]
        public LocationHistory[] GetLocationChangeLog(long? structure_id, DateTime? begin_time, DateTime? end_time)
        {
            return GetLocationChangeLogAsync(structure_id, begin_time, end_time).GetAwaiter().GetResult();
        }
        
    }
}

