// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viking.Identity.Data;

#nullable disable

namespace Viking.Identity.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251002010602_FixExistingUserConcurrencyStamp")]
    partial class FixExistingUserConcurrencyStamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator().HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Viking.Identity.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Viking.Identity.Models.GrantedGroupPermission", b =>
                {
                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResourceId");

                    b.Property<string>("PermissionId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("PermissionId")
                        .HasColumnOrder(2);

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("GranteeType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("ResourceId", "PermissionId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("GrantedGroupPermissions");

                    b.HasDiscriminator<string>("GranteeType").HasValue("Group");
                });

            modelBuilder.Entity("Viking.Identity.Models.GrantedUserPermission", b =>
                {
                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("ResourceId");

                    b.Property<string>("PermissionId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("PermissionId")
                        .HasColumnOrder(2);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GranteeType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("ResourceId", "PermissionId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GrantedUserPermissions");

                    b.HasDiscriminator<string>("GranteeType").HasValue("User");
                });

            modelBuilder.Entity("Viking.Identity.Models.GroupToGroupAssignment", b =>
                {
                    b.Property<long>("ContainerGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("MemberGroupId")
                        .HasColumnType("bigint");

                    b.HasKey("ContainerGroupId", "MemberGroupId");

                    b.HasIndex("MemberGroupId");

                    b.ToTable("GroupToGroupAssignments");
                });

            modelBuilder.Entity("Viking.Identity.Models.Resource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("ParentID")
                        .HasColumnType("bigint");

                    b.Property<string>("ResourceTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ParentID");

                    b.HasIndex("ResourceTypeId");

                    b.ToTable("Resource");

                    b.HasDiscriminator<string>("ResourceTypeId").HasValue("Resource");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Viking.Identity.Models.ResourceType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResourceTypes");

                    b.HasData(
                        new
                        {
                            Id = "Resource"
                        },
                        new
                        {
                            Id = "OrganizationalUnit"
                        },
                        new
                        {
                            Id = "Group"
                        },
                        new
                        {
                            Id = "Volume"
                        });
                });

            modelBuilder.Entity("Viking.Identity.Models.ResourceTypePermission", b =>
                {
                    b.Property<string>("ResourceTypeId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PermissionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("ResourceTypeId", "PermissionId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            ResourceTypeId = "Group",
                            PermissionId = "Access Manager",
                            Description = "Add/Remove group members"
                        },
                        new
                        {
                            ResourceTypeId = "Volume",
                            PermissionId = "Read"
                        },
                        new
                        {
                            ResourceTypeId = "Volume",
                            PermissionId = "Annotate"
                        },
                        new
                        {
                            ResourceTypeId = "Volume",
                            PermissionId = "Review"
                        });
                });

            modelBuilder.Entity("Viking.Identity.Models.UserToGroupAssignment", b =>
                {
                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserToGroupAssignments");
                });

            modelBuilder.Entity("Viking.Identity.Models.ApplicationRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.HasDiscriminator().HasValue("ApplicationRole");

                    b.HasData(
                        new
                        {
                            Id = "cdf2b676-7edc-4d96-9ebb-8d1968734482",
                            Name = "Administrator",
                            NormalizedName = "Administrator"
                        });
                });

            modelBuilder.Entity("Viking.Identity.Models.Group", b =>
                {
                    b.HasBaseType("Viking.Identity.Models.Resource");

                    b.HasDiscriminator().HasValue("Group");

                    b.HasData(
                        new
                        {
                            Id = -1L,
                            Name = "Everyone"
                        });
                });

            modelBuilder.Entity("Viking.Identity.Models.OrganizationalUnit", b =>
                {
                    b.HasBaseType("Viking.Identity.Models.Resource");

                    b.HasDiscriminator().HasValue("OrganizationalUnit");
                });

            modelBuilder.Entity("Viking.Identity.Models.Volume", b =>
                {
                    b.HasBaseType("Viking.Identity.Models.Resource");

                    b.Property<string>("Endpoint")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Volume");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Viking.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Viking.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viking.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Viking.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Viking.Identity.Models.GrantedGroupPermission", b =>
                {
                    b.HasOne("Viking.Identity.Models.Group", "PermittedGroup")
                        .WithMany("PermissionsHeld")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Viking.Identity.Models.Resource", "Resource")
                        .WithMany("GroupsWithPermissions")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermittedGroup");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Viking.Identity.Models.GrantedUserPermission", b =>
                {
                    b.HasOne("Viking.Identity.Models.Resource", "Resource")
                        .WithMany("UsersWithPermissions")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viking.Identity.Models.ApplicationUser", "PermittedUser")
                        .WithMany("PermissionsHeld")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("PermittedUser");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Viking.Identity.Models.GroupToGroupAssignment", b =>
                {
                    b.HasOne("Viking.Identity.Models.Group", "Container")
                        .WithMany("MemberGroups")
                        .HasForeignKey("ContainerGroupId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Viking.Identity.Models.Group", "Member")
                        .WithMany("MemberOfGroups")
                        .HasForeignKey("MemberGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Viking.Identity.Models.Resource", b =>
                {
                    b.HasOne("Viking.Identity.Models.OrganizationalUnit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID");

                    b.HasOne("Viking.Identity.Models.ResourceType", "ResourceType")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("Viking.Identity.Models.ResourceTypePermission", b =>
                {
                    b.HasOne("Viking.Identity.Models.ResourceType", "ResourceType")
                        .WithMany("Permissions")
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("Viking.Identity.Models.UserToGroupAssignment", b =>
                {
                    b.HasOne("Viking.Identity.Models.Group", "Group")
                        .WithMany("MemberUsers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viking.Identity.Models.ApplicationUser", "User")
                        .WithMany("GroupAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Viking.Identity.Models.ApplicationUser", b =>
                {
                    b.Navigation("GroupAssignments");

                    b.Navigation("PermissionsHeld");
                });

            modelBuilder.Entity("Viking.Identity.Models.Resource", b =>
                {
                    b.Navigation("GroupsWithPermissions");

                    b.Navigation("UsersWithPermissions");
                });

            modelBuilder.Entity("Viking.Identity.Models.ResourceType", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Viking.Identity.Models.Group", b =>
                {
                    b.Navigation("MemberGroups");

                    b.Navigation("MemberOfGroups");

                    b.Navigation("MemberUsers");

                    b.Navigation("PermissionsHeld");
                });

            modelBuilder.Entity("Viking.Identity.Models.OrganizationalUnit", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
