<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net48</TargetFramework>
		<LangVersion>9.0</LangVersion>
		<RootNamespace>WebAnnotation.WPF</RootNamespace>
		<AssemblyName>WebAnnotationWPFControls</AssemblyName>
		<UseWPF>true</UseWPF>
		<Deterministic>true</Deterministic>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<ItemGroup> 
		<None Include="**\*.json" /> 
	</ItemGroup>
	<ItemGroup>
	  <Compile Remove=".vs\**" />
	  <Compile Remove="obj\**" />
	  <EmbeddedResource Remove=".vs\**" />
	  <EmbeddedResource Remove="obj\**" />
	  <None Remove=".vs\**" />
	  <None Remove="obj\**" />
	  <Page Remove=".vs\**" />
	  <Page Remove="obj\**" />
	</ItemGroup>
	<ItemGroup>
	  <Page Remove="SampleData\MockFavoriteStructureTypeIDs.xaml" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\AnnotationInterfaces\AnnotationInterfaces.csproj" />
		<ProjectReference Include="..\..\AnnotationServiceTypes\AnnotationServiceTypes.WCF.csproj" />
		<ProjectReference Include="..\WebAnnotationModel\WebAnnotationModel.csproj" />
		<ProjectReference Include="..\WebAnnotationViewModels\WebAnnotationViewModels.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Extended.Wpf.Toolkit" Version="4.0.1" />
		<PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
	</ItemGroup>
</Project>