//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectomeViz.ObjectFileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ObjectFileService.IObjService")]
    public interface IObjService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IObjService/GetObject", ReplyAction="http://tempuri.org/IObjService/GetObjectResponse")]
        string GetObject(string server, string database, string cell, string type, bool update, string virtualPath, string globalPath, string userPath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IObjServiceChannel : ConnectomeViz.ObjectFileService.IObjService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObjServiceClient : System.ServiceModel.ClientBase<ConnectomeViz.ObjectFileService.IObjService>, ConnectomeViz.ObjectFileService.IObjService {
        
        public ObjServiceClient() {
        }
        
        public ObjServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ObjServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObjServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObjServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetObject(string server, string database, string cell, string type, bool update, string virtualPath, string globalPath, string userPath) {
            return base.Channel.GetObject(server, database, cell, type, update, virtualPath, globalPath, userPath);
        }
    }
}
