<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>WebAnnotationTests</RootNamespace>
    <AssemblyName>WebAnnotationTests</AssemblyName>
    <IsCodedUITest>false</IsCodedUITest>
    <TestProjectType>UnitTest</TestProjectType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\GeometryTests\GeometryTests.csproj" />
    <ProjectReference Include="..\..\..\Geometry\Geometry.csproj" />
    <ProjectReference Include="..\..\..\RTree\RTree.csproj" />
    <ProjectReference Include="..\NGVV\VikingCore.csproj" />
    <ProjectReference Include="..\WebAnnotation\WebAnnotation.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="DummyCanvas.cs" />
    <Compile Include="PathAnnotationInteractionTests.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MSTest.TestAdapter" Version="3.9.2" />
    <PackageReference Include="MSTest.TestFramework" Version="3.9.2" />
  </ItemGroup>
</Project>