<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net48;</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>WebAnnotationTests</RootNamespace>
    <AssemblyName>WebAnnotationTests</AssemblyName>
    <IsCodedUITest>false</IsCodedUITest>
    <TestProjectType>UnitTest</TestProjectType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\GeometryTests\GeometryTests.csproj" />
    <ProjectReference Include="..\..\..\Geometry\Geometry.csproj" />
    <ProjectReference Include="..\..\..\RTree\RTree.csproj" />
    <ProjectReference Include="..\NGVV\VikingCore.csproj" />
    <ProjectReference Include="..\WebAnnotation\WebAnnotation.csproj" /> 
    <ProjectReference Include="..\..\Monographics\Monographics.csproj" Condition="'$(TargetFramework)' == 'net9.0-windows'" />
    <ProjectReference Include="..\..\Monographics\Monographics.csproj" Condition="'$(TargetFramework)' == 'net9.0'" />
    <ProjectReference Include="..\..\VikingXNAGraphics\MonographicsNet48.csproj" Condition="'$(TargetFramework)' == 'net48'" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Commands\SegmentationCommandTests.cs" />
    <Compile Include="DummyCanvas.cs" />
    <Compile Include="LocationActionTests.cs" />
    <Compile Include="MouseActionSupportTests.cs" />
    <Compile Include="PathAnnotationInteractionTests.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MSTest.TestAdapter" Version="3.9.3" />
    <PackageReference Include="MSTest.TestFramework" Version="3.9.3" />
  </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
	    <PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
	    <PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0-windows'">
	    <PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
    </ItemGroup>
</Project>