<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Geometry\Geometry.csproj" />
    <ProjectReference Include="..\..\..\SIMeasurement\SIMeasurement.csproj" />
    <ProjectReference Include="..\..\Common\Common.csproj" />
    <ProjectReference Include="..\..\VolumeModel\VolumeModel.csproj" />
    <ProjectReference Include="..\NGVV\VikingCore.csproj" />
    <ProjectReference Include="..\VikingXNAWinForms\VikingXNAWinForms.csproj" />
  </ItemGroup>  
  <ItemGroup>
    <None Include="app.config" />
  </ItemGroup>
</Project>