<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<RootNamespace>AnnotationVizLibTests</RootNamespace>
		<AssemblyName>AnnotationVizLibTests</AssemblyName>
		<OutputType>Library</OutputType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.OData.Client" Version="8.1.0" />
		<PackageReference Include="Microsoft.OData.Core" Version="8.1.0" />
		<PackageReference Include="Microsoft.OData.Edm" Version="8.1.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="protobuf-net" Version="3.2.52" />
		<PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" />
		<PackageReference Include="MSTest.TestFramework" Version="3.9.3" />
		<PackageReference Include="MSTest.TestAdapter" Version="3.9.3" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net48'">
		<PackageReference Include="Microsoft.SqlServer.Types" Version="14.0.1016.290" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\AnnotationInterfaces\AnnotationInterfaces.csproj" />
		<ProjectReference Include="..\AnnotationVizLibODataClient\AnnotationVizLibODataClient.csproj" />
		<ProjectReference Include="..\AnnotationVizLibSimpleODataClient\AnnotationVizLibSimpleODataClient.csproj" />
		<ProjectReference Include="..\AnnotationVizLibWCFClient\AnnotationVizLibWCFClient.csproj" />
		<ProjectReference Include="..\AnnotationVizLib\AnnotationVizLib.csproj" />
		<ProjectReference Include="..\Geometry\Geometry.csproj" />
		<ProjectReference Include="..\GraphLib\GraphLib.csproj" />
		<ProjectReference Include="..\ODataClient\ODataClient.csproj" />
		<ProjectReference Include="..\UnitsAndScale\UnitsAndScale.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="Resources\**\*" CopyToOutputDirectory="PreserveNewest" />
		<None Include="app.config" />
	</ItemGroup>
</Project>
