<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<RootNamespace>VikingXNAWinForms</RootNamespace>
		<AssemblyName>VikingXNAWinForms</AssemblyName>
		<UseWindowsForms>true</UseWindowsForms>
		<MonoGamePlatform>Windows</MonoGamePlatform> 
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.*" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\Geometry\Geometry.csproj" />
		<ProjectReference Include="..\..\Monographics\Monographics.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Include="app.config" />
	</ItemGroup>
</Project>