<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net45</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>UserRegistration</RootNamespace>
    <AssemblyName>UserRegistration</AssemblyName>
    <UseIISExpress>true</UseIISExpress>
    <AutoAssignPort>true</AutoAssignPort>
    <DevelopmentServerPort>18086</DevelopmentServerPort>
    <DevelopmentServerVPath>/</DevelopmentServerVPath>
    <IISUrl>http://localhost:18086/</IISUrl>
    <NTLMAuthentication>false</NTLMAuthentication>
    <UseCustomServer>false</UseCustomServer>
    <SaveServerSettingsInUserFile>false</SaveServerSettingsInUserFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.1.0" />
    <PackageReference Include="Microsoft.AspNet.Identity.Core" Version="2.2.1" />
    <PackageReference Include="Microsoft.AspNet.Identity.EntityFramework" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="packages.config" />
    <Content Include="Register.aspx" />
    <Content Include="Web.config" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Host\Host.csproj" />
  </ItemGroup>

</Project>