<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>MorphologyView</RootNamespace>
    <AssemblyName>MorphologyView</AssemblyName>
    <OutputType>Library</OutputType>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <OutputPath Condition="'$(Configuration)' == 'Debug'">..\Jotunn\bin\Debug\Modules\MorphologyView\</OutputPath>
    <OutputPath Condition="'$(Configuration)' == 'Release'">..\Jotunn\bin\Release\Modules\MorphologyView\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.2.0" />
    <PackageReference Include="MathNet.Numerics" Version="4.15.0" />
    <PackageReference Include="CommonServiceLocator" Version="1.3" />
    <PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.19" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.5.1.1679" />
    <PackageReference Include="MonoGame.Framework.WpfInterop" Version="1.5.0" />
    <PackageReference Include="Prism.Core" Version="6.2.0" />
    <PackageReference Include="Prism.Mef" Version="6.2.0" />
    <PackageReference Include="Prism.Wpf" Version="6.2.0" />
    <PackageReference Include="System.Buffers" Version="4.6.1" />
    <PackageReference Include="System.Collections.Immutable" Version="9.0.7" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.5.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\AnnotationInterfaces\AnnotationInterfaces.csproj" />
    <ProjectReference Include="..\..\..\AnnotationVizLib\AnnotationVizLib.csproj" />
    <ProjectReference Include="..\..\..\AnnotationVizLibSimpleODataClient\AnnotationVizLibSimpleODataClient.csproj" />
    <ProjectReference Include="..\..\..\Geometry\Geometry.csproj" />
    <ProjectReference Include="..\..\..\GraphLib\GraphLib.csproj" />
    <ProjectReference Include="..\..\..\RTree\RTree.csproj" />
    <ProjectReference Include="..\..\..\SqlGeometryUtils\SqlGeometryUtils.csproj" />
    <ProjectReference Include="..\..\Common\Common.csproj" />
    <ProjectReference Include="..\JotunnCommon\JotunnUICommon.csproj" />
    <ProjectReference Include="..\MonogameWPFLibrary\MonogameWPFLibrary.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="app.config" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="SqlServerTypes\readme.htm" />
    <Content Include="SqlServerTypes\x64\msvcr120.dll" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="SqlServerTypes\x64\SqlServerSpatial140.dll" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="SqlServerTypes\x86\msvcr120.dll" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="SqlServerTypes\x86\SqlServerSpatial140.dll" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if not exist &quot;$(SolutionDir)Jotunn\Jotunn\Modules\$(TargetName)&quot; mkdir &quot;$(SolutionDir)Jotunn\Jotunn\Modules\$(TargetName)&quot;" />
    <Exec Command="copy $(TargetDir)\*.dll &quot;$(SolutionDir)Jotunn\Jotunn\Modules\$(TargetName)&quot;" />
    <Exec Command="copy $(TargetDir)\*.pdb &quot;$(SolutionDir)Jotunn\Jotunn\Modules\$(TargetName)&quot;" />
  </Target>
  
  <Import Project="..\..\..\Packages\MathNet.Numerics.MKL.Win.2.5.0\build\MathNet.Numerics.MKL.Win.targets" Condition="Exists('..\..\..\Packages\MathNet.Numerics.MKL.Win.2.5.0\build\MathNet.Numerics.MKL.Win.targets')" />
</Project>