<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net9.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Geometry\Geometry.csproj" />
    <ProjectReference Include="..\SqlGeometryUtils\SqlGeometryUtils.csproj" />
    <ProjectReference Include="..\AnnotationServiceTypes\AnnotationServiceTypes.WCF.csproj" />
    <ProjectReference Include="..\Clients\WebAnnotationModel\WebAnnotationModel.csproj" />
    <ProjectReference Include="..\Clients\VolumeModel\VolumeModel.csproj" />
  </ItemGroup>
	  <!-- Conditional Package References -->
	<ItemGroup Condition="'$(TargetFramework)' == 'net48'">
		<PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
		<PackageReference Include="System.Memory" Version="4.6.3" />
	</ItemGroup>
	  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
		  <PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
	  </ItemGroup>
	  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0-windows'">
		  <PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
	  </ItemGroup>
</Project>