// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Viking.DataModel.Annotation;

namespace Viking.DataModel.Annotation
{
    public partial class AnnotationContext
    {
        private AnnotationContextProcedures _procedures;

        public virtual AnnotationContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new AnnotationContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public AnnotationContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ApproximateStructureLocationResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<ApproximateStructureLocationsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<CountChildStructuresByTypeResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<DeepDeleteStructureResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<MergeStructuresResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<RecursiveSelectChildStructureIDsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectAllStructureLocationLinksResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectAllStructureLocationsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectAllStructuresResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectChildrenStructureLinksResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectChildStructureCenters3DResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectLastModifiedLocationByUsersResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectNearestChildAttachLocationCandidatesResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectNearestParentAttachCandidatesForLocationsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectNearestParentAttachLocationCandidatesResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectNetworkChildStructureIDsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectNetworkChildStructuresResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectNetworkChildStructureSpatialDataResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectNetworkDetailsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectNetworkStructureIDsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectNetworkStructureLinksResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectNetworkStructuresResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectNetworkStructureSpatialDataResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectNumConnectionsPerStructureResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectRootStructuresResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectSectionAnnotationsInMosaicBoundsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectSectionAnnotationsInVolumeBoundsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectSectionLocationLinksResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectSectionLocationLinksInMosaicBoundsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectSectionLocationLinksInVolumeBoundsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectSectionLocationsAndLinksResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectSectionLocationsAndLinksInMosaicBoundsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectSectionLocationsAndLinksInVolumeBoundsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectSectionStructuresResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectSectionStructuresAndLinksResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectSectionStructuresAndLinksInMosaicBoundsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectSectionStructuresAndLinksInVolumeBoundsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectSectionStructuresInMosaicBoundsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectSectionStructuresInVolumeBoundsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectStructureResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectStructureChangeLogResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectStructureLabelsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectStructureLocationChangeLogResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectStructureLocationLinksResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectStructureLocationLinksNoChildrenResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectStructureLocationsResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectStructureLocationsAndLinksResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectStructuresAndLinksResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectStructuresLinkedViaChildrenResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectUnfinishedStructureBranchesResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SelectUnfinishedStructureBranchesWithPositionResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SplitStructureResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<SplitStructureAtLocationLinkResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<UpdateStructureTypeResult>().HasNoKey().ToView(null);
        }
    }

    public interface IAnnotationContextProceduresContract
    {
        Task<List<ApproximateStructureLocationResult>> ApproximateStructureLocationAsync(int? StructureID, CancellationToken cancellationToken = default);
        Task<List<ApproximateStructureLocationsResult>> ApproximateStructureLocationsAsync(CancellationToken cancellationToken = default);
        Task<List<CountChildStructuresByTypeResult>> CountChildStructuresByTypeAsync(long? StructureID, CancellationToken cancellationToken = default);
        Task<List<DeepDeleteStructureResult>> DeepDeleteStructureAsync(long? DeleteID, CancellationToken cancellationToken = default);
        Task<List<MergeStructuresResult>> MergeStructuresAsync(long? KeepStructureID, long? MergeStructureID, CancellationToken cancellationToken = default);
        Task<List<RecursiveSelectChildStructureIDsResult>> RecursiveSelectChildStructureIDsAsync(DataTable IDs, CancellationToken cancellationToken = default);
        Task<List<SelectAllStructureLocationLinksResult>> SelectAllStructureLocationLinksAsync(CancellationToken cancellationToken = default);
        Task<List<SelectAllStructureLocationsResult>> SelectAllStructureLocationsAsync(CancellationToken cancellationToken = default);
        Task<List<SelectAllStructuresResult>> SelectAllStructuresAsync(CancellationToken cancellationToken = default);
        Task<List<SelectChildrenStructureLinksResult>> SelectChildrenStructureLinksAsync(long? StructureID, CancellationToken cancellationToken = default);
        Task<List<SelectChildStructureCenters3DResult>> SelectChildStructureCenters3DAsync(CancellationToken cancellationToken = default);
        Task<List<SelectLastModifiedLocationByUsersResult>> SelectLastModifiedLocationByUsersAsync(CancellationToken cancellationToken = default);
        Task<List<SelectNearestChildAttachLocationCandidatesResult>> SelectNearestChildAttachLocationCandidatesAsync(DataTable ParentStructureIDs, CancellationToken cancellationToken = default);
        Task<List<SelectNearestParentAttachCandidatesForLocationsResult>> SelectNearestParentAttachCandidatesForLocationsAsync(DataTable ChildLocIDs, CancellationToken cancellationToken = default);
        Task<List<SelectNearestParentAttachLocationCandidatesResult>> SelectNearestParentAttachLocationCandidatesAsync(DataTable ChildStructureIDs, CancellationToken cancellationToken = default);
        Task<List<SelectNetworkChildStructureIDsResult>> SelectNetworkChildStructureIDsAsync(DataTable IDs, int? Hops, CancellationToken cancellationToken = default);
        Task<List<SelectNetworkChildStructuresResult>> SelectNetworkChildStructuresAsync(DataTable IDs, int? Hops, CancellationToken cancellationToken = default);
        Task<List<SelectNetworkChildStructureSpatialDataResult>> SelectNetworkChildStructureSpatialDataAsync(DataTable IDs, int? Hops, CancellationToken cancellationToken = default);
        Task<List<SelectNetworkDetailsResult>> SelectNetworkDetailsAsync(DataTable IDs, int? Hops, CancellationToken cancellationToken = default);
        Task<List<SelectNetworkStructureIDsResult>> SelectNetworkStructureIDsAsync(DataTable IDs, int? Hops, CancellationToken cancellationToken = default);
        Task<List<SelectNetworkStructureLinksResult>> SelectNetworkStructureLinksAsync(DataTable IDs, int? Hops, CancellationToken cancellationToken = default);
        Task<List<SelectNetworkStructuresResult>> SelectNetworkStructuresAsync(DataTable IDs, int? Hops, CancellationToken cancellationToken = default);
        Task<List<SelectNetworkStructureSpatialDataResult>> SelectNetworkStructureSpatialDataAsync(DataTable IDs, int? Hops, CancellationToken cancellationToken = default);
        Task<List<SelectNumConnectionsPerStructureResult>> SelectNumConnectionsPerStructureAsync(CancellationToken cancellationToken = default);
        Task<List<SelectRootStructuresResult>> SelectRootStructuresAsync(CancellationToken cancellationToken = default);
        Task<List<SelectSectionAnnotationsInMosaicBoundsResult>> SelectSectionAnnotationsInMosaicBoundsAsync(double? Z, byte[] BBox, double? MinRadius, DateTime? QueryDate, CancellationToken cancellationToken = default);
        Task<List<SelectSectionAnnotationsInVolumeBoundsResult>> SelectSectionAnnotationsInVolumeBoundsAsync(double? Z, byte[] BBox, double? MinRadius, DateTime? QueryDate, CancellationToken cancellationToken = default);
        Task<List<SelectSectionLocationLinksResult>> SelectSectionLocationLinksAsync(double? Z, DateTime? QueryDate, CancellationToken cancellationToken = default);
        Task<List<SelectSectionLocationLinksInMosaicBoundsResult>> SelectSectionLocationLinksInMosaicBoundsAsync(double? Z, byte[] bbox, double? MinRadius, DateTime? QueryDate, CancellationToken cancellationToken = default);
        Task<List<SelectSectionLocationLinksInVolumeBoundsResult>> SelectSectionLocationLinksInVolumeBoundsAsync(double? Z, byte[] bbox, double? MinRadius, DateTime? QueryDate, CancellationToken cancellationToken = default);
        Task<List<SelectSectionLocationsAndLinksResult>> SelectSectionLocationsAndLinksAsync(double? Z, DateTime? QueryDate, CancellationToken cancellationToken = default);
        Task<List<SelectSectionLocationsAndLinksInMosaicBoundsResult>> SelectSectionLocationsAndLinksInMosaicBoundsAsync(double? Z, byte[] BBox, double? Radius, DateTime? QueryDate, CancellationToken cancellationToken = default);
        Task<List<SelectSectionLocationsAndLinksInVolumeBoundsResult>> SelectSectionLocationsAndLinksInVolumeBoundsAsync(double? Z, byte[] BBox, double? Radius, DateTime? QueryDate, CancellationToken cancellationToken = default);
        Task<List<SelectSectionStructuresResult>> SelectSectionStructuresAsync(double? Z, DateTime? QueryDate, CancellationToken cancellationToken = default);
        Task<List<SelectSectionStructuresAndLinksResult>> SelectSectionStructuresAndLinksAsync(double? Z, DateTime? QueryDate, CancellationToken cancellationToken = default);
        Task<List<SelectSectionStructuresAndLinksInMosaicBoundsResult>> SelectSectionStructuresAndLinksInMosaicBoundsAsync(double? Z, byte[] BBox, double? MinRadius, DateTime? QueryDate, CancellationToken cancellationToken = default);
        Task<List<SelectSectionStructuresAndLinksInVolumeBoundsResult>> SelectSectionStructuresAndLinksInVolumeBoundsAsync(double? Z, byte[] BBox, double? MinRadius, DateTime? QueryDate, CancellationToken cancellationToken = default);
        Task<List<SelectSectionStructuresInMosaicBoundsResult>> SelectSectionStructuresInMosaicBoundsAsync(double? Z, byte[] BBox, double? MinRadius, DateTime? QueryDate, CancellationToken cancellationToken = default);
        Task<List<SelectSectionStructuresInVolumeBoundsResult>> SelectSectionStructuresInVolumeBoundsAsync(double? Z, byte[] BBox, double? MinRadius, DateTime? QueryDate, CancellationToken cancellationToken = default);
        Task<List<SelectStructureResult>> SelectStructureAsync(long? StructureID, CancellationToken cancellationToken = default);
        Task<List<SelectStructureChangeLogResult>> SelectStructureChangeLogAsync(long? structure_ID, DateTime? begin_time, DateTime? end_time, CancellationToken cancellationToken = default);
        Task<List<SelectStructureLabelsResult>> SelectStructureLabelsAsync(CancellationToken cancellationToken = default);
        Task<List<SelectStructureLocationChangeLogResult>> SelectStructureLocationChangeLogAsync(long? structure_ID, DateTime? begin_time, DateTime? end_time, CancellationToken cancellationToken = default);
        Task<List<SelectStructureLocationLinksResult>> SelectStructureLocationLinksAsync(long? StructureID, CancellationToken cancellationToken = default);
        Task<List<SelectStructureLocationLinksNoChildrenResult>> SelectStructureLocationLinksNoChildrenAsync(long? StructureID, CancellationToken cancellationToken = default);
        Task<List<SelectStructureLocationsResult>> SelectStructureLocationsAsync(long? StructureID, CancellationToken cancellationToken = default);
        Task<List<SelectStructureLocationsAndLinksResult>> SelectStructureLocationsAndLinksAsync(long? StructureID, CancellationToken cancellationToken = default);
        Task<List<SelectStructuresAndLinksResult>> SelectStructuresAndLinksAsync(CancellationToken cancellationToken = default);
        Task<List<SelectStructuresLinkedViaChildrenResult>> SelectStructuresLinkedViaChildrenAsync(long? ID, CancellationToken cancellationToken = default);
        Task<List<SelectUnfinishedStructureBranchesResult>> SelectUnfinishedStructureBranchesAsync(long? StructureID, CancellationToken cancellationToken = default);
        Task<List<SelectUnfinishedStructureBranchesWithPositionResult>> SelectUnfinishedStructureBranchesWithPositionAsync(long? StructureID, CancellationToken cancellationToken = default);
        Task<List<SplitStructureResult>> SplitStructureAsync(long? LocationIDOfSplitStructure, CancellationToken cancellationToken = default);
        Task<List<SplitStructureAtLocationLinkResult>> SplitStructureAtLocationLinkAsync(long? LocationIDOfKeepStructure, long? LocationIDOfSplitStructure, CancellationToken cancellationToken = default);
        Task<int> UpdateStructureTypeAsync(long? StructureID, long? TypeID, CancellationToken cancellationToken = default);
    }

    public partial class AnnotationContextProcedures
    {
        private readonly AnnotationContext _context;

        public AnnotationContextProcedures(AnnotationContext context)
        {
            _context = context;
        }

        public virtual async Task<List<ApproximateStructureLocationResult>> ApproximateStructureLocationAsync(int? StructureID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "StructureID",
                    Value = StructureID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<ApproximateStructureLocationResult>("EXEC @returnValue = [dbo].[ApproximateStructureLocation] @StructureID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<ApproximateStructureLocationsResult>> ApproximateStructureLocationsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<ApproximateStructureLocationsResult>("EXEC @returnValue = [dbo].[ApproximateStructureLocations]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<CountChildStructuresByTypeResult>> CountChildStructuresByTypeAsync(long? StructureID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "StructureID",
                    Value = StructureID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<CountChildStructuresByTypeResult>("EXEC @returnValue = [dbo].[CountChildStructuresByType] @StructureID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<DeepDeleteStructureResult>> DeepDeleteStructureAsync(long? DeleteID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "DeleteID",
                    Value = DeleteID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<DeepDeleteStructureResult>("EXEC @returnValue = [dbo].[DeepDeleteStructure] @DeleteID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<MergeStructuresResult>> MergeStructuresAsync(long? KeepStructureID, long? MergeStructureID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "KeepStructureID",
                    Value = KeepStructureID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "MergeStructureID",
                    Value = MergeStructureID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<MergeStructuresResult>("EXEC @returnValue = [dbo].[MergeStructures] @KeepStructureID, @MergeStructureID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        

        public virtual async Task<List<SelectAllStructureLocationLinksResult>> SelectAllStructureLocationLinksAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectAllStructureLocationLinksResult>("EXEC @returnValue = [dbo].[SelectAllStructureLocationLinks]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectAllStructureLocationsResult>> SelectAllStructureLocationsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectAllStructureLocationsResult>("EXEC @returnValue = [dbo].[SelectAllStructureLocations]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectAllStructuresResult>> SelectAllStructuresAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectAllStructuresResult>("EXEC @returnValue = [dbo].[SelectAllStructures]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectChildrenStructureLinksResult>> SelectChildrenStructureLinksAsync(long? StructureID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "StructureID",
                    Value = StructureID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectChildrenStructureLinksResult>("EXEC @returnValue = [dbo].[SelectChildrenStructureLinks] @StructureID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectChildStructureCenters3DResult>> SelectChildStructureCenters3DAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectChildStructureCenters3DResult>("EXEC @returnValue = [dbo].[SelectChildStructureCenters3D]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectLastModifiedLocationByUsersResult>> SelectLastModifiedLocationByUsersAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectLastModifiedLocationByUsersResult>("EXEC @returnValue = [dbo].[SelectLastModifiedLocationByUsers]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectNearestChildAttachLocationCandidatesResult>> SelectNearestChildAttachLocationCandidatesAsync(DataTable ParentStructureIDs, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ParentStructureIDs",
                    Value = ParentStructureIDs ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[zz_integer_list]",
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectNearestChildAttachLocationCandidatesResult>("EXEC @returnValue = [dbo].[SelectNearestChildAttachLocationCandidates] @ParentStructureIDs", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectNearestParentAttachCandidatesForLocationsResult>> SelectNearestParentAttachCandidatesForLocationsAsync(DataTable ChildLocIDs, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ChildLocIDs",
                    Value = ChildLocIDs ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[zz_integer_list]",
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectNearestParentAttachCandidatesForLocationsResult>("EXEC @returnValue = [dbo].[SelectNearestParentAttachCandidatesForLocations] @ChildLocIDs", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectNearestParentAttachLocationCandidatesResult>> SelectNearestParentAttachLocationCandidatesAsync(DataTable ChildStructureIDs, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ChildStructureIDs",
                    Value = ChildStructureIDs ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[zz_integer_list]",
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectNearestParentAttachLocationCandidatesResult>("EXEC @returnValue = [dbo].[SelectNearestParentAttachLocationCandidates] @ChildStructureIDs", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectNetworkChildStructureIDsResult>> SelectNetworkChildStructureIDsAsync(DataTable IDs, int? Hops, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IDs",
                    Value = IDs ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[zz_integer_list]",
                },
                new SqlParameter
                {
                    ParameterName = "Hops",
                    Value = Hops ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectNetworkChildStructureIDsResult>("EXEC @returnValue = [dbo].[SelectNetworkChildStructureIDs] @IDs, @Hops", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectNetworkChildStructuresResult>> SelectNetworkChildStructuresAsync(DataTable IDs, int? Hops, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IDs",
                    Value = IDs ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[zz_integer_list]",
                },
                new SqlParameter
                {
                    ParameterName = "Hops",
                    Value = Hops ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectNetworkChildStructuresResult>("EXEC @returnValue = [dbo].[SelectNetworkChildStructures] @IDs, @Hops", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectNetworkChildStructureSpatialDataResult>> SelectNetworkChildStructureSpatialDataAsync(DataTable IDs, int? Hops, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IDs",
                    Value = IDs ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[zz_integer_list]",
                },
                new SqlParameter
                {
                    ParameterName = "Hops",
                    Value = Hops ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectNetworkChildStructureSpatialDataResult>("EXEC @returnValue = [dbo].[SelectNetworkChildStructureSpatialData] @IDs, @Hops", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectNetworkDetailsResult>> SelectNetworkDetailsAsync(DataTable IDs, int? Hops, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IDs",
                    Value = IDs ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[zz_integer_list]",
                },
                new SqlParameter
                {
                    ParameterName = "Hops",
                    Value = Hops ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectNetworkDetailsResult>("EXEC @returnValue = [dbo].[SelectNetworkDetails] @IDs, @Hops", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectNetworkStructureIDsResult>> SelectNetworkStructureIDsAsync(DataTable IDs, int? Hops, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IDs",
                    Value = IDs ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[zz_integer_list]",
                },
                new SqlParameter
                {
                    ParameterName = "Hops",
                    Value = Hops ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectNetworkStructureIDsResult>("EXEC @returnValue = [dbo].[SelectNetworkStructureIDs] @IDs, @Hops", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectNetworkStructureLinksResult>> SelectNetworkStructureLinksAsync(DataTable IDs, int? Hops, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IDs",
                    Value = IDs ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[zz_integer_list]",
                },
                new SqlParameter
                {
                    ParameterName = "Hops",
                    Value = Hops ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectNetworkStructureLinksResult>("EXEC @returnValue = [dbo].[SelectNetworkStructureLinks] @IDs, @Hops", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectNetworkStructuresResult>> SelectNetworkStructuresAsync(DataTable IDs, int? Hops, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IDs",
                    Value = IDs ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[zz_integer_list]",
                },
                new SqlParameter
                {
                    ParameterName = "Hops",
                    Value = Hops ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectNetworkStructuresResult>("EXEC @returnValue = [dbo].[SelectNetworkStructures] @IDs, @Hops", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectNetworkStructureSpatialDataResult>> SelectNetworkStructureSpatialDataAsync(DataTable IDs, int? Hops, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "IDs",
                    Value = IDs ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Structured,
                    TypeName = "[dbo].[zz_integer_list]",
                },
                new SqlParameter
                {
                    ParameterName = "Hops",
                    Value = Hops ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectNetworkStructureSpatialDataResult>("EXEC @returnValue = [dbo].[SelectNetworkStructureSpatialData] @IDs, @Hops", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectNumConnectionsPerStructureResult>> SelectNumConnectionsPerStructureAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectNumConnectionsPerStructureResult>("EXEC @returnValue = [dbo].[SelectNumConnectionsPerStructure]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectRootStructuresResult>> SelectRootStructuresAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectRootStructuresResult>("EXEC @returnValue = [dbo].[SelectRootStructures]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectSectionAnnotationsInMosaicBoundsResult>> SelectSectionAnnotationsInMosaicBoundsAsync(double? Z, byte[] BBox, double? MinRadius, DateTime? QueryDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Z",
                    Value = Z ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "BBox",
                    Value = BBox ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Udt,
                    UdtTypeName = "geometry",
                },
                new SqlParameter
                {
                    ParameterName = "MinRadius",
                    Value = MinRadius ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "QueryDate",
                    Value = QueryDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectSectionAnnotationsInMosaicBoundsResult>("EXEC @returnValue = [dbo].[SelectSectionAnnotationsInMosaicBounds] @Z, @BBox, @MinRadius, @QueryDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectSectionAnnotationsInVolumeBoundsResult>> SelectSectionAnnotationsInVolumeBoundsAsync(double? Z, byte[] BBox, double? MinRadius, DateTime? QueryDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Z",
                    Value = Z ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "BBox",
                    Value = BBox ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Udt,
                    UdtTypeName = "geometry",
                },
                new SqlParameter
                {
                    ParameterName = "MinRadius",
                    Value = MinRadius ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "QueryDate",
                    Value = QueryDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectSectionAnnotationsInVolumeBoundsResult>("EXEC @returnValue = [dbo].[SelectSectionAnnotationsInVolumeBounds] @Z, @BBox, @MinRadius, @QueryDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectSectionLocationLinksResult>> SelectSectionLocationLinksAsync(double? Z, DateTime? QueryDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Z",
                    Value = Z ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "QueryDate",
                    Value = QueryDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectSectionLocationLinksResult>("EXEC @returnValue = [dbo].[SelectSectionLocationLinks] @Z, @QueryDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectSectionLocationLinksInMosaicBoundsResult>> SelectSectionLocationLinksInMosaicBoundsAsync(double? Z, byte[] bbox, double? MinRadius, DateTime? QueryDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Z",
                    Value = Z ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "bbox",
                    Value = bbox ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Udt,
                    UdtTypeName = "geometry",
                },
                new SqlParameter
                {
                    ParameterName = "MinRadius",
                    Value = MinRadius ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "QueryDate",
                    Value = QueryDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectSectionLocationLinksInMosaicBoundsResult>("EXEC @returnValue = [dbo].[SelectSectionLocationLinksInMosaicBounds] @Z, @bbox, @MinRadius, @QueryDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectSectionLocationLinksInVolumeBoundsResult>> SelectSectionLocationLinksInVolumeBoundsAsync(double? Z, byte[] bbox, double? MinRadius, DateTime? QueryDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Z",
                    Value = Z ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "bbox",
                    Value = bbox ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Udt,
                    UdtTypeName = "geometry",
                },
                new SqlParameter
                {
                    ParameterName = "MinRadius",
                    Value = MinRadius ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "QueryDate",
                    Value = QueryDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectSectionLocationLinksInVolumeBoundsResult>("EXEC @returnValue = [dbo].[SelectSectionLocationLinksInVolumeBounds] @Z, @bbox, @MinRadius, @QueryDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectSectionLocationsAndLinksResult>> SelectSectionLocationsAndLinksAsync(double? Z, DateTime? QueryDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Z",
                    Value = Z ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "QueryDate",
                    Value = QueryDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectSectionLocationsAndLinksResult>("EXEC @returnValue = [dbo].[SelectSectionLocationsAndLinks] @Z, @QueryDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectSectionLocationsAndLinksInMosaicBoundsResult>> SelectSectionLocationsAndLinksInMosaicBoundsAsync(double? Z, byte[] BBox, double? Radius, DateTime? QueryDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Z",
                    Value = Z ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "BBox",
                    Value = BBox ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Udt,
                    UdtTypeName = "geometry",
                },
                new SqlParameter
                {
                    ParameterName = "Radius",
                    Value = Radius ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "QueryDate",
                    Value = QueryDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectSectionLocationsAndLinksInMosaicBoundsResult>("EXEC @returnValue = [dbo].[SelectSectionLocationsAndLinksInMosaicBounds] @Z, @BBox, @Radius, @QueryDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectSectionLocationsAndLinksInVolumeBoundsResult>> SelectSectionLocationsAndLinksInVolumeBoundsAsync(double? Z, byte[] BBox, double? Radius, DateTime? QueryDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Z",
                    Value = Z ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "BBox",
                    Value = BBox ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Udt,
                    UdtTypeName = "geometry",
                },
                new SqlParameter
                {
                    ParameterName = "Radius",
                    Value = Radius ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "QueryDate",
                    Value = QueryDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectSectionLocationsAndLinksInVolumeBoundsResult>("EXEC @returnValue = [dbo].[SelectSectionLocationsAndLinksInVolumeBounds] @Z, @BBox, @Radius, @QueryDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectSectionStructuresResult>> SelectSectionStructuresAsync(double? Z, DateTime? QueryDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Z",
                    Value = Z ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "QueryDate",
                    Value = QueryDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectSectionStructuresResult>("EXEC @returnValue = [dbo].[SelectSectionStructures] @Z, @QueryDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectSectionStructuresAndLinksResult>> SelectSectionStructuresAndLinksAsync(double? Z, DateTime? QueryDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Z",
                    Value = Z ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "QueryDate",
                    Value = QueryDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectSectionStructuresAndLinksResult>("EXEC @returnValue = [dbo].[SelectSectionStructuresAndLinks] @Z, @QueryDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectSectionStructuresAndLinksInMosaicBoundsResult>> SelectSectionStructuresAndLinksInMosaicBoundsAsync(double? Z, byte[] BBox, double? MinRadius, DateTime? QueryDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Z",
                    Value = Z ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "BBox",
                    Value = BBox ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Udt,
                    UdtTypeName = "geometry",
                },
                new SqlParameter
                {
                    ParameterName = "MinRadius",
                    Value = MinRadius ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "QueryDate",
                    Value = QueryDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectSectionStructuresAndLinksInMosaicBoundsResult>("EXEC @returnValue = [dbo].[SelectSectionStructuresAndLinksInMosaicBounds] @Z, @BBox, @MinRadius, @QueryDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectSectionStructuresAndLinksInVolumeBoundsResult>> SelectSectionStructuresAndLinksInVolumeBoundsAsync(double? Z, byte[] BBox, double? MinRadius, DateTime? QueryDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Z",
                    Value = Z ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "BBox",
                    Value = BBox ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Udt,
                    UdtTypeName = "geometry",
                },
                new SqlParameter
                {
                    ParameterName = "MinRadius",
                    Value = MinRadius ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "QueryDate",
                    Value = QueryDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectSectionStructuresAndLinksInVolumeBoundsResult>("EXEC @returnValue = [dbo].[SelectSectionStructuresAndLinksInVolumeBounds] @Z, @BBox, @MinRadius, @QueryDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectSectionStructuresInMosaicBoundsResult>> SelectSectionStructuresInMosaicBoundsAsync(double? Z, byte[] BBox, double? MinRadius, DateTime? QueryDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Z",
                    Value = Z ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "BBox",
                    Value = BBox ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Udt,
                    UdtTypeName = "geometry",
                },
                new SqlParameter
                {
                    ParameterName = "MinRadius",
                    Value = MinRadius ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "QueryDate",
                    Value = QueryDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectSectionStructuresInMosaicBoundsResult>("EXEC @returnValue = [dbo].[SelectSectionStructuresInMosaicBounds] @Z, @BBox, @MinRadius, @QueryDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectSectionStructuresInVolumeBoundsResult>> SelectSectionStructuresInVolumeBoundsAsync(double? Z, byte[] BBox, double? MinRadius, DateTime? QueryDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Z",
                    Value = Z ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "BBox",
                    Value = BBox ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Udt,
                    UdtTypeName = "geometry",
                },
                new SqlParameter
                {
                    ParameterName = "MinRadius",
                    Value = MinRadius ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Float,
                },
                new SqlParameter
                {
                    ParameterName = "QueryDate",
                    Value = QueryDate ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectSectionStructuresInVolumeBoundsResult>("EXEC @returnValue = [dbo].[SelectSectionStructuresInVolumeBounds] @Z, @BBox, @MinRadius, @QueryDate", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectStructureResult>> SelectStructureAsync(long? StructureID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "StructureID",
                    Value = StructureID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectStructureResult>("EXEC @returnValue = [dbo].[SelectStructure] @StructureID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectStructureChangeLogResult>> SelectStructureChangeLogAsync(long? structure_ID, DateTime? begin_time, DateTime? end_time, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "structure_ID",
                    Value = structure_ID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "begin_time",
                    Value = begin_time ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "end_time",
                    Value = end_time ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectStructureChangeLogResult>("EXEC @returnValue = [dbo].[SelectStructureChangeLog] @structure_ID, @begin_time, @end_time", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectStructureLabelsResult>> SelectStructureLabelsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectStructureLabelsResult>("EXEC @returnValue = [dbo].[SelectStructureLabels]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectStructureLocationChangeLogResult>> SelectStructureLocationChangeLogAsync(long? structure_ID, DateTime? begin_time, DateTime? end_time, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "structure_ID",
                    Value = structure_ID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "begin_time",
                    Value = begin_time ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "end_time",
                    Value = end_time ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectStructureLocationChangeLogResult>("EXEC @returnValue = [dbo].[SelectStructureLocationChangeLog] @structure_ID, @begin_time, @end_time", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectStructureLocationLinksResult>> SelectStructureLocationLinksAsync(long? StructureID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "StructureID",
                    Value = StructureID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectStructureLocationLinksResult>("EXEC @returnValue = [dbo].[SelectStructureLocationLinks] @StructureID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectStructureLocationLinksNoChildrenResult>> SelectStructureLocationLinksNoChildrenAsync(long? StructureID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "StructureID",
                    Value = StructureID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectStructureLocationLinksNoChildrenResult>("EXEC @returnValue = [dbo].[SelectStructureLocationLinksNoChildren] @StructureID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectStructureLocationsResult>> SelectStructureLocationsAsync(long? StructureID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "StructureID",
                    Value = StructureID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectStructureLocationsResult>("EXEC @returnValue = [dbo].[SelectStructureLocations] @StructureID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectStructureLocationsAndLinksResult>> SelectStructureLocationsAndLinksAsync(long? StructureID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "StructureID",
                    Value = StructureID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectStructureLocationsAndLinksResult>("EXEC @returnValue = [dbo].[SelectStructureLocationsAndLinks] @StructureID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectStructuresAndLinksResult>> SelectStructuresAndLinksAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectStructuresAndLinksResult>("EXEC @returnValue = [dbo].[SelectStructuresAndLinks]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectStructuresLinkedViaChildrenResult>> SelectStructuresLinkedViaChildrenAsync(long? ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ID",
                    Value = ID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectStructuresLinkedViaChildrenResult>("EXEC @returnValue = [dbo].[SelectStructuresLinkedViaChildren] @ID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectUnfinishedStructureBranchesResult>> SelectUnfinishedStructureBranchesAsync(long? StructureID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "StructureID",
                    Value = StructureID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectUnfinishedStructureBranchesResult>("EXEC @returnValue = [dbo].[SelectUnfinishedStructureBranches] @StructureID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SelectUnfinishedStructureBranchesWithPositionResult>> SelectUnfinishedStructureBranchesWithPositionAsync(long? StructureID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "StructureID",
                    Value = StructureID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SelectUnfinishedStructureBranchesWithPositionResult>("EXEC @returnValue = [dbo].[SelectUnfinishedStructureBranchesWithPosition] @StructureID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SplitStructureResult>> SplitStructureAsync(long? LocationIDOfSplitStructure, OutputParameter<long?> SplitStructureID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterSplitStructureID = new SqlParameter
            {
                ParameterName = "SplitStructureID",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = SplitStructureID?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.BigInt,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "LocationIDOfSplitStructure",
                    Value = LocationIDOfSplitStructure ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterSplitStructureID,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SplitStructureResult>("EXEC @returnValue = [dbo].[SplitStructure] @LocationIDOfSplitStructure, @SplitStructureID OUTPUT", sqlParameters, cancellationToken);

            SplitStructureID.SetValue(parameterSplitStructureID.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SplitStructureAtLocationLinkResult>> SplitStructureAtLocationLinkAsync(long? LocationIDOfKeepStructure, long? LocationIDOfSplitStructure, OutputParameter<long?> SplitStructureID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterSplitStructureID = new SqlParameter
            {
                ParameterName = "SplitStructureID",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = SplitStructureID?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.BigInt,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "LocationIDOfKeepStructure",
                    Value = LocationIDOfKeepStructure ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "LocationIDOfSplitStructure",
                    Value = LocationIDOfSplitStructure ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterSplitStructureID,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<SplitStructureAtLocationLinkResult>("EXEC @returnValue = [dbo].[SplitStructureAtLocationLink] @LocationIDOfKeepStructure, @LocationIDOfSplitStructure, @SplitStructureID OUTPUT", sqlParameters, cancellationToken);

            SplitStructureID.SetValue(parameterSplitStructureID.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> UpdateStructureTypeAsync(long? StructureID, long? TypeID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "StructureID",
                    Value = StructureID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "TypeID",
                    Value = TypeID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[UpdateStructureType] @StructureID, @TypeID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
