// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;

namespace Viking.DataModel.Annotation
{
    public partial class AnnotationContext
    {

        [DbFunction("XYScaleUnits", "dbo")]
        public static string XYScaleUnits()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("ZScaleUnits", "dbo")]
        public static string ZScaleUnits()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("XYScale", "dbo")]
        public static double? XYScale()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("ZScale", "dbo")]
        public static double? ZScale()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }
    }
}
