<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Viking.DataModel.Annotation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Partials\**" />
    <EmbeddedResource Remove="Partials\**" />
    <None Remove="Partials\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Viking\DataModel\Annotation\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EfCore.SchemaCompare" Version="6.0.0" />
    <PackageReference Include="EntityFrameworkExtras.EFCore" Version="6.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" Version="6.0.4" />
  </ItemGroup>

</Project>
