// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Viking.DataModel.Annotation
{
    public partial class CountChildStructuresByTypeResult
    {
        public long TypeID { get; set; }
        public int? Count { get; set; }
    }
}
