// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Viking.DataModel.Annotation
{
    public partial class DeletedLocation
    {
        [Key]
        [Column("ID")]
        public long Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DeletedOn { get; set; }
    }
}