// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Viking.DataModel.Annotation
{
    [Table("PermittedStructureLink")]
    [Index(nameof(SourceTypeId), nameof(TargetTypeId), Name = "PermittedStructureLink_source_target_unique", IsUnique = true)]
    public partial class PermittedStructureLink
    {
        [Key]
        [Column("SourceTypeID")]
        public long SourceTypeId { get; set; }
        [Key]
        [Column("TargetTypeID")]
        public long TargetTypeId { get; set; }
        public bool Bidirectional { get; set; }

        [ForeignKey(nameof(SourceTypeId))]
        [InverseProperty(nameof(StructureType.PermittedStructureLinkSourceTypes))]
        public virtual StructureType SourceType { get; set; }
        [ForeignKey(nameof(TargetTypeId))]
        [InverseProperty(nameof(StructureType.PermittedStructureLinkTargetTypes))]
        public virtual StructureType TargetType { get; set; }
    }
}