// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Viking.DataModel.Annotation
{
    public partial class SelectUnfinishedStructureBranchesWithPositionResult
    {
        public long ID { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
        public long Z { get; set; }
        public double? Radius { get; set; }
    }
}
