// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Viking.DataModel.Annotation
{
    public partial class StructureLocationLinksResult
    {
        public long A { get; set; }
        public long B { get; set; }
        public string Username { get; set; }
        public DateTime Created { get; set; }
    }
}
