<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net48;net9.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>false</GenerateBindingRedirectsOutputType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)' == 'net48'">
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
		<Optimize>false</Optimize>
		<OutputPath>bin\Debug\</OutputPath>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DebugType>pdbonly</DebugType>
		<Optimize>true</Optimize>
		<OutputPath>bin\Release\</OutputPath>
		<DefineConstants></DefineConstants>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<!-- Project references -->
	<ItemGroup>
		<ProjectReference Include="..\Geometry\Geometry.csproj" />
		<ProjectReference Include="..\UnitsAndScale\UnitsAndScale.csproj" />
	</ItemGroup>
	<!-- NuGet package references -->
	<ItemGroup>
		<PackageReference Include="MathNet.Numerics" Version="5.0.0" /> 
		<PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" />
		<PackageReference Include="System.Memory" Version="4.6.3" />
	</ItemGroup>
	
	<!-- SQL Server Types - different versions for different frameworks -->
	<ItemGroup Condition="'$(TargetFramework)' == 'net48'">
		<PackageReference Include="EntityFramework" Version="6.4.4" />
		<PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0' or '$(TargetFramework)' == 'netstandard2.0'">
		<PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="SqlServerTypes\" />
	</ItemGroup>
</Project>