<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Identity.DataContext\Identity.DataContext.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IdentityModel.AspNetCore" Version="4.3.0" />
    <PackageReference Include="IdentityModel.AspNetCore.AccessTokenValidation" Version="1.0.0-preview.0" />
    <PackageReference Include="IdentityModel.AspNetCore.OAuth2Introspection" Version="6.2.0" />
    <PackageReference Include="Duende.IdentityServer" Version="7.3.1" />
    <PackageReference Include="Duende.IdentityServer.AspNetIdentity" Version="7.3.1" />
    <PackageReference Include="Duende.IdentityServer.EntityFramework" Version="7.3.1" />
  </ItemGroup>

</Project>
