<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>Viking</RootNamespace>
    <AssemblyName>Viking</AssemblyName>
    <ApplicationIcon>Viking.ico</ApplicationIcon>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <SignAssembly>false</SignAssembly>
    <ManifestTimestampUrl>http://timestamp.digicert.com</ManifestTimestampUrl>
    <AssemblyOriginatorKeyFile>Viking_1_TemporaryKey.pfx</AssemblyOriginatorKeyFile>
    <ProductName>Viking</ProductName>
    <PublisherName>Marc Lab</PublisherName>
    <ApplicationVersion>1.1.0.0</ApplicationVersion>
    <FileVersion>1.1.0.0</FileVersion>
    <Deterministic>false</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="EntityFramework" Version="6.5.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NGVV\VikingCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
  </ItemGroup>
</Project>