<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    
    <PackageReference Include="MathNet.Numerics.Providers.MKL" Version="5.0.0" />
    <PackageReference Include="MathNet.Numerics.MKL.Win-x64" Version="3.0.0" />
    <PackageReference Include="MathNet.Numerics.MKL.Linux-x64" Version="2.0.0" />
    <PackageReference Include="MathNet.Numerics.Providers.OpenBLAS" Version="5.0.0" />
	  
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Collections.Immutable" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Clients\Common\Common.csproj" />
    <ProjectReference Include="..\GraphLib\GraphLib.csproj" />
    <ProjectReference Include="..\RTree\RTree.csproj" />
    <ProjectReference Include="..\UnitsAndScale\UnitsAndScale.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\Utils\Utils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Primitives\Enumerators\" />
  </ItemGroup>

</Project>
