<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>AnnotationUtilsTests</RootNamespace>
    <AssemblyName>AnnotationUtilsTests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="3.1.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GraphLib\GraphLib.csproj" />
    <ProjectReference Include="..\AnnotationGraphLib\AnnotationGraphLib.csproj" />
  </ItemGroup>
</Project>