//
// This code was generated by Visual ReCode 2.0.3.1140
//

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Google.Protobuf;
using Grpc.Core;
using gRPCAnnotationServiceCore.Protos;

namespace gRPCAnnotationServiceCore.Services
{
    public partial class AnnotateLocations : global::gRPCAnnotationServiceCore.Protos.AnnotateLocations.AnnotateLocationsBase
    {
            private readonly AnnotationService.Interfaces.IAnnotateLocations _serviceContract;
            private readonly ILogger<AnnotateLocations> _logger;
        
        public AnnotateLocations(AnnotationService.Interfaces.IAnnotateLocations serviceContract, ILogger<AnnotateLocations> logger)
        {
            _serviceContract = serviceContract;
            _logger = logger;
        }
        
        public override Task<Protos.CreateLocationResponse> CreateLocation(Protos.CreateLocationRequest request, ServerCallContext context)
        {
            try
            {
                var returnValue = _serviceContract.CreateLocation((global::AnnotationService.Types.Location)request.Obj, request.LinkedIds.ToArray());
                var response = new Protos.CreateLocationResponse { Value = (Protos.Location)returnValue };
                return Task.FromResult(response);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error invoking CreateLocation");
                throw new RpcException(new Status(StatusCode.Internal, ex.Message));
            }
        }
        
        public override Task<Protos.GetLocationByIDResponse> GetLocationByID(Protos.GetLocationByIDRequest request, ServerCallContext context)
        {
            try
            {
                var returnValue = _serviceContract.GetLocationByID(request.Id);
                var response = new Protos.GetLocationByIDResponse { Value = (Protos.Location)returnValue };
                return Task.FromResult(response);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error invoking GetLocationByID");
                throw new RpcException(new Status(StatusCode.Internal, ex.Message));
            }
        }
        
        public override Task<Protos.GetLocationsByIDResponse> GetLocationsByID(Protos.GetLocationsByIDRequest request, ServerCallContext context)
        {
            try
            {
                var returnValue = _serviceContract.GetLocationsByID(request.Ids.ToArray());
                var response = new Protos.GetLocationsByIDResponse();
                response.Values.AddRange(returnValue.Select(x => (Protos.Location)x));
                return Task.FromResult(response);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error invoking GetLocationsByID");
                throw new RpcException(new Status(StatusCode.Internal, ex.Message));
            }
        }
        
        public override Task<Protos.GetLastModifiedLocationResponse> GetLastModifiedLocation(Protos.GetLastModifiedLocationRequest request, ServerCallContext context)
        {
            try
            {
                var returnValue = _serviceContract.GetLastModifiedLocation();
                var response = new Protos.GetLastModifiedLocationResponse { Value = (Protos.Location)returnValue };
                return Task.FromResult(response);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error invoking GetLastModifiedLocation");
                throw new RpcException(new Status(StatusCode.Internal, ex.Message));
            }
        }
        
        public override Task<Protos.GetLinkedLocationsResponse> GetLinkedLocations(Protos.GetLinkedLocationsRequest request, ServerCallContext context)
        {
            try
            {
                var returnValue = _serviceContract.GetLinkedLocations(request.Id);
                var response = new Protos.GetLinkedLocationsResponse();
                response.Values.AddRange(returnValue);
                return Task.FromResult(response);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error invoking GetLinkedLocations");
                throw new RpcException(new Status(StatusCode.Internal, ex.Message));
            }
        }
        
        public override Task<Protos.GetLocationsForSectionResponse> GetLocationsForSection(Protos.GetLocationsForSectionRequest request, ServerCallContext context)
        {
            try
            {
                var returnValue = _serviceContract.GetLocationsForSection(request.Section, request.QueryExecutedTime);
                var response = new Protos.GetLocationsForSectionResponse();
                response.Values.AddRange(returnValue.Select(x => (Protos.Location)x));
                return Task.FromResult(response);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error invoking GetLocationsForSection");
                throw new RpcException(new Status(StatusCode.Internal, ex.Message));
            }
        }
        
        public override Task<Protos.GetLocationsForStructureResponse> GetLocationsForStructure(Protos.GetLocationsForStructureRequest request, ServerCallContext context)
        {
            try
            {
                var returnValue = _serviceContract.GetLocationsForStructure(request.StructureId);
                var response = new Protos.GetLocationsForStructureResponse();
                response.Values.AddRange(returnValue.Select(x => (Protos.Location)x));
                return Task.FromResult(response);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error invoking GetLocationsForStructure");
                throw new RpcException(new Status(StatusCode.Internal, ex.Message));
            }
        }
        
        public override Task<Protos.GetLocationChangesInMosaicRegionResponse> GetLocationChangesInMosaicRegion(Protos.GetLocationChangesInMosaicRegionRequest request, ServerCallContext context)
        {
            try
            {
                var returnValue = _serviceContract.GetLocationChangesInMosaicRegion(request.Section, (global::AnnotationService.Types.BoundingRectangle)request.Bbox, request.MinRadius, request.ModifiedAfterThisUtcTime, request.QueryExecutedTime, request.DeletedIds.ToArray());
                var response = new Protos.GetLocationChangesInMosaicRegionResponse();
                response.Values.AddRange(returnValue.Select(x => (Protos.Location)x));
                return Task.FromResult(response);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error invoking GetLocationChangesInMosaicRegion");
                throw new RpcException(new Status(StatusCode.Internal, ex.Message));
            }
        }
        
        public override Task<Protos.GetAnnotationsInMosaicRegionResponse> GetAnnotationsInMosaicRegion(Protos.GetAnnotationsInMosaicRegionRequest request, ServerCallContext context)
        {
            try
            {
                var returnValue = _serviceContract.GetAnnotationsInMosaicRegion(request.Section, (global::AnnotationService.Types.BoundingRectangle)request.Bbox, request.MinRadius, request.ModifiedAfterThisUtcTime, request.QueryExecutedTime, request.DeletedIds.ToArray());
                var response = new Protos.GetAnnotationsInMosaicRegionResponse { Value = (Protos.AnnotationSet)returnValue };
                return Task.FromResult(response);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error invoking GetAnnotationsInMosaicRegion");
                throw new RpcException(new Status(StatusCode.Internal, ex.Message));
            }
        }
        
        public override Task<Protos.GetLocationChangesResponse> GetLocationChanges(Protos.GetLocationChangesRequest request, ServerCallContext context)
        {
            try
            {
                var returnValue = _serviceContract.GetLocationChanges(request.Section, request.ModifiedAfterThisUtcTime, request.QueryExecutedTime, request.DeletedIds.ToArray());
                var response = new Protos.GetLocationChangesResponse();
                response.Values.AddRange(returnValue.Select(x => (Protos.Location)x));
                return Task.FromResult(response);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error invoking GetLocationChanges");
                throw new RpcException(new Status(StatusCode.Internal, ex.Message));
            }
        }
        
        public override Task<Protos.UpdateResponse> Update(Protos.UpdateRequest request, ServerCallContext context)
        {
            try
            {
                var returnValue = _serviceContract.Update(request.Locations.Select(x => (global::AnnotationService.Types.Location)x).ToArray());
                var response = new Protos.UpdateResponse();
                response.Values.AddRange(returnValue);
                return Task.FromResult(response);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error invoking Update");
                throw new RpcException(new Status(StatusCode.Internal, ex.Message));
            }
        }
        
        public override Task<Protos.CreateLocationLinkResponse> CreateLocationLink(Protos.CreateLocationLinkRequest request, ServerCallContext context)
        {
            try
            {
                _serviceContract.CreateLocationLink(request.SourceId, request.TargetId);
                return Task.FromResult(new Protos.CreateLocationLinkResponse());
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error invoking CreateLocationLink");
                throw new RpcException(new Status(StatusCode.Internal, ex.Message));
            }
        }
        
        public override Task<Protos.DeleteLocationLinkResponse> DeleteLocationLink(Protos.DeleteLocationLinkRequest request, ServerCallContext context)
        {
            try
            {
                _serviceContract.DeleteLocationLink(request.SourceId, request.TargetId);
                return Task.FromResult(new Protos.DeleteLocationLinkResponse());
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error invoking DeleteLocationLink");
                throw new RpcException(new Status(StatusCode.Internal, ex.Message));
            }
        }
        
        public override Task<Protos.GetLocationLinksForSectionResponse> GetLocationLinksForSection(Protos.GetLocationLinksForSectionRequest request, ServerCallContext context)
        {
            try
            {
                var returnValue = _serviceContract.GetLocationLinksForSection(request.Section, request.ModifiedAfterThisTime, request.QueryExecutedTime, request.DeletedLinks.Select(x => (global::AnnotationService.Types.LocationLink)x).ToArray());
                var response = new Protos.GetLocationLinksForSectionResponse();
                response.Values.AddRange(returnValue.Select(x => (Protos.LocationLink)x));
                return Task.FromResult(response);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error invoking GetLocationLinksForSection");
                throw new RpcException(new Status(StatusCode.Internal, ex.Message));
            }
        }
        
        public override Task<Protos.GetLocationLinksForSectionInMosaicRegionResponse> GetLocationLinksForSectionInMosaicRegion(Protos.GetLocationLinksForSectionInMosaicRegionRequest request, ServerCallContext context)
        {
            try
            {
                var returnValue = _serviceContract.GetLocationLinksForSectionInMosaicRegion(request.Section, (global::AnnotationService.Types.BoundingRectangle)request.Bbox, request.MinRadius, request.ModifiedAfterThisUtcTime, request.QueryExecutedTime, request.DeletedLinks.Select(x => (global::AnnotationService.Types.LocationLink)x).ToArray());
                var response = new Protos.GetLocationLinksForSectionInMosaicRegionResponse();
                response.Values.AddRange(returnValue.Select(x => (Protos.LocationLink)x));
                return Task.FromResult(response);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error invoking GetLocationLinksForSectionInMosaicRegion");
                throw new RpcException(new Status(StatusCode.Internal, ex.Message));
            }
        }
        
        public override Task<Protos.GetLocationChangeLogResponse> GetLocationChangeLog(Protos.GetLocationChangeLogRequest request, ServerCallContext context)
        {
            try
            {
                var returnValue = _serviceContract.GetLocationChangeLog(request.StructureId, request.BeginTime, request.EndTime);
                var response = new Protos.GetLocationChangeLogResponse();
                response.Values.AddRange(returnValue.Select(x => (Protos.LocationHistory)x));
                return Task.FromResult(response);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error invoking GetLocationChangeLog");
                throw new RpcException(new Status(StatusCode.Internal, ex.Message));
            }
        }
        
    }
}

