<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
  <LangVersion>latest</LangVersion>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>VikingTests</RootNamespace>
    <AssemblyName>VikingTests</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common\Common.csproj" />
    <ProjectReference Include="..\NGVV\VikingCore.csproj" />
  </ItemGroup> 
  <ItemGroup>
    <None Include="app.config" />
    <None Include="AuthoringTests.txt" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="3.9.3" />
  </ItemGroup>
</Project>
