<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Neo4JService.Tests</RootNamespace>
    <AssemblyName>Neo4JService.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="3.1.2" />
    <PackageReference Include="Neo4j.Driver" Version="5.15.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.9" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="5.2.9" />
    <PackageReference Include="Microsoft.AspNet.WebApi.WebHost" Version="5.2.9" />
    <PackageReference Include="Microsoft.AspNet.Mvc" Version="5.2.9" />
    <PackageReference Include="Microsoft.AspNet.Razor" Version="3.2.9" />
    <PackageReference Include="Microsoft.AspNet.WebPages" Version="3.2.9" />
    <PackageReference Include="Microsoft.Web.Infrastructure" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Neo4JService\Neo4JService.csproj" />
    <ProjectReference Include="..\WebAppSettings\VikingWebAppSettings.csproj" />
  </ItemGroup>
</Project>