<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>SqlServerTypesLoader</AssemblyName>
    <RootNamespace>SqlServerTypesLoader</RootNamespace>
    <Description>SDK for loading SQL Server native spatial assemblies</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
