<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<RootNamespace>Annotation.ViewModels</RootNamespace>
		<AssemblyName>Annotation.ViewModels</AssemblyName>
		<UseWPF>true</UseWPF>
		<Deterministic>true</Deterministic>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\AnnotationInterfaces\AnnotationInterfaces.csproj" />
		<ProjectReference Include="..\..\AnnotationServiceTypes\AnnotationServiceTypes.WCF.csproj" />
		<ProjectReference Include="..\WebAnnotationModel\WebAnnotationModel.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Include="app.config" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
	</ItemGroup>
</Project>