<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net48;netstandard2.0</TargetFrameworks>
		<RootNamespace>AnnotationServiceTypes</RootNamespace>
		<AssemblyName>AnnotationServiceTypes</AssemblyName>
		<Version>1.0.0.0</Version>
		<Copyright>Copyright © 2017</Copyright>
		<OutputType>Library</OutputType>
		<LangVersion>latest</LangVersion>
		<AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>false</GenerateBindingRedirectsOutputType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net48'">
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Properties\**" />
	  <EmbeddedResource Remove="Properties\**" />
	  <None Remove="Properties\**" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="protobuf-net" Version="3.2.56" />
		<PackageReference Include="protobuf-net.ServiceModel" Version="3.2.52" />
		<PackageReference Include="System.Runtime.Serialization.Primitives" Version="4.3.0" />
		<PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" /> 
		
	</ItemGroup>
	
	<!-- Entity Framework 6 is only available for .NET Framework -->
	<ItemGroup Condition="'$(TargetFramework)' == 'net48'">
		<PackageReference Include="EntityFramework" Version="6.5.1" />
		<Reference Include="System.ServiceModel" />
	</ItemGroup>

	<!-- WCF primitives for .NET Standard -->
	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
		<PackageReference Include="System.ServiceModel.Primitives" Version="8.1.2" />
	</ItemGroup>
	<ItemGroup>
		<WCFMetadata Include="Connected Services\" />
	</ItemGroup>
</Project>
