<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net45</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>AspNetIdentity.Tests</RootNamespace>
    <AssemblyName>AspNetIdentity.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.Identity.Core" Version="2.0.1" />
    <PackageReference Include="xunit" Version="1.9.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="app.config" />
    <None Include="packages.config" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspNetIdentity\AspNetIdentity.csproj" />
    <ProjectReference Include="..\Core.Tests\Core.Tests.csproj" />
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

</Project>