<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<RootNamespace>WebAnnotationModelTest</RootNamespace>
		<AssemblyName>WebAnnotationModelTest</AssemblyName>
		<Deterministic>true</Deterministic>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DefineConstants>DEBUG;TRACE</DefineConstants>
		<Optimize>false</Optimize>
		<OutputPath>bin\Debug\</OutputPath>
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DefineConstants>TRACE</DefineConstants>
		<Optimize>true</Optimize>
		<OutputPath>bin\Release\</OutputPath>
		<DebugType>pdbonly</DebugType>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="System" />
		<Reference Include="System.Core" />
		<Reference Include="System.Net.Http" />
		<Reference Include="System.Numerics" />
		<Reference Include="System.Runtime.Serialization" />
		<Reference Include="System.ServiceModel" />
	</ItemGroup>
	<ItemGroup> 
		<None Include="app.config" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\AnnotationInterfaces\AnnotationInterfaces.csproj" />
		<ProjectReference Include="..\..\AnnotationServiceTypes\AnnotationServiceTypes.WCF.csproj" />
		<ProjectReference Include="..\..\Geometry\Geometry.csproj" />
		<ProjectReference Include="..\..\RTree\RTree.csproj" />
		<ProjectReference Include="..\..\SIMeasurement\SIMeasurement.csproj" />
		<ProjectReference Include="..\Viking\WebAnnotation\WebAnnotation.csproj" />
		<ProjectReference Include="..\WCFTokenInjector\WCFTokenInjector.csproj" />
		<ProjectReference Include="..\WebAnnotationModel\WebAnnotationModel.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Duende.IdentityModel" Version="7.1.0" />
		<PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
		<PackageReference Include="System.Memory" Version="4.6.3" />
		<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
		<PackageReference Include="System.Text.Json" Version="9.0.7" />
		<PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
		<PackageReference Include="System.ValueTuple" Version="4.6.1" />
		<PackageReference Include="MSTest.TestFramework" Version="3.9.3" />
	</ItemGroup>
</Project>
