<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net48</TargetFramework>
		<LangVersion>9.0</LangVersion>
		<RootNamespace>VikingXNAGraphics</RootNamespace>
		<AssemblyName>VikingXNAGraphics</AssemblyName>
		<UseWindowsForms>true</UseWindowsForms>
		<MonoGamePlatform>Windows</MonoGamePlatform>
		<NoWarn>$(NoWarn);CA1014</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.7.1.189" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Geometry\Geometry.csproj" />
		<ProjectReference Include="..\..\Triangle.NET\Triangle\Triangle.csproj" />
		<ProjectReference Include="..\..\TriangleNetGeometryExtensions\TriangleNetGeometryExtensions.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Compile Include="..\MonogameXNAGraphicsShared\**\*.cs" Exclude="..\MonogameXNAGraphicsShared\obj\**;..\MonogameXNAGraphicsShared\bin\**"></Compile> 
		<Content Include="..\MonogameXNAGraphicsShared\Content\bin\Windows\**\*.xnb">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Link>Content\%(Filename)%(Extension)</Link>
		</Content>
		<None Include="..\MonogameXNAGraphicsShared\Content\**\*.fx"> 
			<Link>Content\%(RecursiveDir)%(Filename)%(Extension)</Link>
		</None>
	</ItemGroup>
	<ItemGroup>
		<Reference Include="MonoGame.Framework">
			<HintPath>$(NuGetPackageRoot)\monogame.framework.windowsdx\3.7.1\lib\net45\MonoGame.Framework.dll</HintPath>
		</Reference>
	</ItemGroup>
	<Target Name="CompileContent" BeforeTargets="Build">
		<Exec
			Command="&quot;C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\MGCB.exe&quot; /quiet /@:&quot;Content.mgcb&quot; /platform:Windows /outputDir:&quot;bin/Windows&quot; /intermediateDir:&quot;obj/Windows&quot;"
			WorkingDirectory="$(MSBuildThisFileDirectory)..\MonogameXNAGraphicsShared\Content" />
	</Target>
</Project> 