<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net48</TargetFramework>
		<LangVersion>9.0</LangVersion>
		<RootNamespace>VikingXNAGraphics</RootNamespace>
		<AssemblyName>VikingXNAGraphics</AssemblyName>
		<UseWindowsForms>true</UseWindowsForms>
		<MonoGamePlatform>Windows</MonoGamePlatform>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.7.1.189" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Geometry\Geometry.csproj" />
		<ProjectReference Include="..\..\Triangle.NET\Triangle\Triangle.csproj" />
		<ProjectReference Include="..\..\TriangleNetGeometryExtensions\TriangleNetGeometryExtensions.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Compile Include="..\MonogameXNAGraphicsShared\**\*.cs" Exclude="..\MonogameXNAGraphicsShared\obj\**;..\MonogameXNAGraphicsShared\bin\**"></Compile> 
		<Content Include="..\MonogameXNAGraphicsShared\**\*.fx"></Content>
		<Content Include="..\MonogameXNAGraphicsShared\**\*.mgcb"></Content>
		<Content Include="..\MonogameXNAGraphicsShared\**\*.png"></Content>
	</ItemGroup>
	<ItemGroup>
		<Reference Include="MonoGame.Framework">
			<HintPath>$(NuGetPackageRoot)\monogame.framework.windowsdx\3.7.1\lib\net45\MonoGame.Framework.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project> 