<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FsCheck" Version="3.3.0" />
    <PackageReference Include="MSTest.TestFramework" Version="3.9.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GeometryTests\GeometryTests.csproj" />
    <ProjectReference Include="..\Geometry\Geometry.csproj" />
  </ItemGroup>
</Project>