<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FsCheck" Version="2.16.3" />
    <PackageReference Include="MSTest.TestFramework" Version="3.9.3" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.9.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GeometryTests\GeometryTests.csproj" />
    <ProjectReference Include="..\Geometry\Geometry.csproj" />
    <ProjectReference Include="..\MorphologyMesh\MorphologyMesh.csproj" />
    <ProjectReference Include="..\AnnotationVizLibODataClient\AnnotationVizLibODataClient.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Testdata\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
