<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net48;net9.0</TargetFrameworks>
		<RootNamespace>AnnotationVizLib</RootNamespace>
		<AssemblyName>AnnotationVizLib</AssemblyName>
		<OutputType>Library</OutputType>
		<LangVersion>9.0</LangVersion>
		<SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
		<Description>Cross-platform image processing library.</Description>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\AnnotationInterfaces\AnnotationInterfaces.csproj" />
		<ProjectReference Include="..\Geometry\Geometry.csproj" />
		<ProjectReference Include="..\SqlGeometryUtils\SqlGeometryUtils.csproj" />
		<ProjectReference Include="..\Triangle.NET\Triangle\Triangle.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="EntityFramework" Version="6.5.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="System.Drawing.Common" Version="9.0.7" />
		<PackageReference Include="System.Text.Json" Version="9.0.7" />
		<PackageReference Include="System.Memory" Version="4.6.3" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.9" Condition="'$(TargetFramework)' == 'net9.0'" />
	</ItemGroup>
</Project>