<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>MeasureDistance</RootNamespace>
    <AssemblyName>MeasureDistance</AssemblyName>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Microsoft.OData.Client" Version="6.15.0" />
    <PackageReference Include="Microsoft.OData.Core" Version="6.15.0" />
    <PackageReference Include="Microsoft.OData.Edm" Version="6.15.0" />
    <PackageReference Include="Microsoft.Spatial" Version="6.15.0" />
    <PackageReference Include="Simple.OData.V4.Client" Version="4.24.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\AnnotationVizLib\AnnotationVizLib.csproj" />
    <ProjectReference Include="..\..\Geometry\Geometry.csproj" />
    <ProjectReference Include="..\..\GraphLib\GraphLib.csproj" />
    <ProjectReference Include="..\..\ODataClient\ODataClient.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>
</Project>