<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>false</GenerateBindingRedirectsOutputType>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Geometry\Geometry.csproj" />
    <ProjectReference Include="..\UnitsAndScale\UnitsAndScale.csproj" />
    <ProjectReference Include="..\SqlGeometryUtils\SqlGeometryUtils.csproj" />
    <ProjectReference Include="..\AnnotationVizLib\AnnotationVizLib.csproj" />
    <ProjectReference Include="..\ODataClient\ODataClient.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.OData.Client" Version="8.1.0" />
    <PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
  </ItemGroup>
</Project>