//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viking.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%UserProfile%")]
        public string LastTileExportDirectory {
            get {
                return ((string)(this["LastTileExportDirectory"]));
            }
            set {
                this["LastTileExportDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal LastExportRangeStart {
            get {
                return ((decimal)(this["LastExportRangeStart"]));
            }
            set {
                this["LastExportRangeStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal LastExportRangeEnd {
            get {
                return ((decimal)(this["LastExportRangeEnd"]));
            }
            set {
                this["LastExportRangeEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportAllChecked {
            get {
                return ((bool)(this["ExportAllChecked"]));
            }
            set {
                this["ExportAllChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal LastTileExportDownsampleLevel {
            get {
                return ((decimal)(this["LastTileExportDownsampleLevel"]));
            }
            set {
                this["LastTileExportDownsampleLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%UserProfile%")]
        public string LastFrameCaptureExportDirectory {
            get {
                return ((string)(this["LastFrameCaptureExportDirectory"]));
            }
            set {
                this["LastFrameCaptureExportDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FrameCaptureDefaultPrefix {
            get {
                return ((string)(this["FrameCaptureDefaultPrefix"]));
            }
            set {
                this["FrameCaptureDefaultPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExportFramesIncludeOverlays {
            get {
                return ((bool)(this["ExportFramesIncludeOverlays"]));
            }
            set {
                this["ExportFramesIncludeOverlays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal ExportFramesFirstFrameNumber {
            get {
                return ((decimal)(this["ExportFramesFirstFrameNumber"]));
            }
            set {
                this["ExportFramesFirstFrameNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string LastGotoX {
            get {
                return ((string)(this["LastGotoX"]));
            }
            set {
                this["LastGotoX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string LastGotoY {
            get {
                return ((string)(this["LastGotoY"]));
            }
            set {
                this["LastGotoY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string LastGotoZ {
            get {
                return ((string)(this["LastGotoZ"]));
            }
            set {
                this["LastGotoZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public string LastDownsample {
            get {
                return ((string)(this["LastDownsample"]));
            }
            set {
                this["LastDownsample"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%UserProfile%\\Pictures")]
        public string LastScreenshotPath {
            get {
                return ((string)(this["LastScreenshotPath"]));
            }
            set {
                this["LastScreenshotPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LastScreenshotIncludeOverlays {
            get {
                return ((bool)(this["LastScreenshotIncludeOverlays"]));
            }
            set {
                this["LastScreenshotIncludeOverlays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LastScreenshotUseViewersDownsampleLevel {
            get {
                return ((bool)(this["LastScreenshotUseViewersDownsampleLevel"]));
            }
            set {
                this["LastScreenshotUseViewersDownsampleLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CachedUsername {
            get {
                return ((string)(this["CachedUsername"]));
            }
            set {
                this["CachedUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>http://storage1.connectomes.utah.edu/</string>
  <string>http://internal.connectomes.utah.edu/</string>
  <string>http://openconnecto.me/ocp/ca/</string>
  <string>http://v2486.host.s.uw.edu/</string>
  <string>http://connectomes.utah.edu/</string>
  <string>http://storage2.connectomes.utah.edu/</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ServerURLs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ServerURLs"]));
            }
            set {
                this["ServerURLs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCommandHelp {
            get {
                return ((bool)(this["ShowCommandHelp"]));
            }
            set {
                this["ShowCommandHelp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>http://connectomes.utah.edu/Rabbit</string>
  <string>http://internal.connectomes.utah.edu/RC2/SliceToVolume.VikingXML</string>
  <string>http://storage1.connectomes.utah.edu/RPC1/SliceToVolume.VikingXML </string>
  <string>http://storage2.connectomes.utah.edu/RPC2/SliceToVolume.VikingXML</string>
  <string>http://storage2.connectomes.utah.edu/RPC3/SliceToVolume.VikingXML</string>
  <string>http://storage2.connectomes.utah.edu/RC3/SliceToVolume.VikingXML</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection VolumeURLs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VolumeURLs"]));
            }
            set {
                this["VolumeURLs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FrameExportPrefix {
            get {
                return ((string)(this["FrameExportPrefix"]));
            }
            set {
                this["FrameExportPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FrameExportPath {
            get {
                return ((string)(this["FrameExportPath"]));
            }
            set {
                this["FrameExportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ScreenShot")]
        public string ScreenShotFilePrefix {
            get {
                return ((string)(this["ScreenShotFilePrefix"]));
            }
            set {
                this["ScreenShotFilePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ScreenShotNumber {
            get {
                return ((int)(this["ScreenShotNumber"]));
            }
            set {
                this["ScreenShotNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://identity.codepharm.net:5001/")]
        public string IdentityServerURL {
            get {
                return ((string)(this["IdentityServerURL"]));
            }
            set {
                this["IdentityServerURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SectionNumberOverlayEnabled {
            get {
                return ((bool)(this["SectionNumberOverlayEnabled"]));
            }
            set {
                this["SectionNumberOverlayEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int SectionNumberOverlayCount {
            get {
                return ((int)(this["SectionNumberOverlayCount"]));
            }
            set {
                this["SectionNumberOverlayCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double SectionNumberOverlayAcceleration {
            get {
                return ((double)(this["SectionNumberOverlayAcceleration"]));
            }
            set {
                this["SectionNumberOverlayAcceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public string SectionNumberOverlayEdge {
            get {
                return ((string)(this["SectionNumberOverlayEdge"]));
            }
            set {
                this["SectionNumberOverlayEdge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double SectionNumberOverlayOpacity {
            get {
                return ((double)(this["SectionNumberOverlayOpacity"]));
            }
            set {
                this["SectionNumberOverlayOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public double SectionNumberOverlayMinOpacityNonCenter {
            get {
                return ((double)(this["SectionNumberOverlayMinOpacityNonCenter"]));
            }
            set {
                this["SectionNumberOverlayMinOpacityNonCenter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double SectionNumberOverlayCenterMagnification {
            get {
                return ((double)(this["SectionNumberOverlayCenterMagnification"]));
            }
            set {
                this["SectionNumberOverlayCenterMagnification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double SectionNumberOverlayPidProportionalGain {
            get {
                return ((double)(this["SectionNumberOverlayPidProportionalGain"]));
            }
            set {
                this["SectionNumberOverlayPidProportionalGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300.0")]
        public double SectionNumberOverlayPidDerivativeGain {
            get {
                return ((double)(this["SectionNumberOverlayPidDerivativeGain"]));
            }
            set {
                this["SectionNumberOverlayPidDerivativeGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public double SectionNumberOverlayPidIntegralGain {
            get {
                return ((double)(this["SectionNumberOverlayPidIntegralGain"]));
            }
            set {
                this["SectionNumberOverlayPidIntegralGain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public double SectionNumberOverlayPidVelocityThreshold {
            get {
                return ((double)(this["SectionNumberOverlayPidVelocityThreshold"]));
            }
            set {
                this["SectionNumberOverlayPidVelocityThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public double SectionNumberOverlayPidPositionThreshold {
            get {
                return ((double)(this["SectionNumberOverlayPidPositionThreshold"]));
            }
            set {
                this["SectionNumberOverlayPidPositionThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int TextureLoadingWindow {
            get {
                return ((int)(this["TextureLoadingWindow"]));
            }
            set {
                this["TextureLoadingWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MinTexturesToLoadFromQueue {
            get {
                return ((int)(this["MinTexturesToLoadFromQueue"]));
            }
            set {
                this["MinTexturesToLoadFromQueue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int VisibleTileSortIntervalMs {
            get {
                return ((int)(this["VisibleTileSortIntervalMs"]));
            }
            set {
                this["VisibleTileSortIntervalMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MaxConcurrentTextureRequests {
            get {
                return ((int)(this["MaxConcurrentTextureRequests"]));
            }
            set {
                this["MaxConcurrentTextureRequests"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoadAdjacentSectionTextures {
            get {
                return ((bool)(this["LoadAdjacentSectionTextures"]));
            }
            set {
                this["LoadAdjacentSectionTextures"] = value;
            }
        }
    }
}
