<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48</TargetFrameworks>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>
  
  <!-- Framework references -->
  <ItemGroup>
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.ServiceModel.Web" />
  </ItemGroup>
  
  <!-- Project references -->
  <ItemGroup>
    <ProjectReference Include="..\Geometry\Geometry.csproj" />
    <ProjectReference Include="..\UnitsAndScale\UnitsAndScale.csproj" />
    <ProjectReference Include="..\AnnotationServiceTypes\AnnotationServiceTypes.WCF.csproj" />
    <ProjectReference Include="..\AnnotationVizLib\AnnotationVizLib.csproj" />
    <ProjectReference Include="..\SqlGeometryUtils\SqlGeometryUtils.csproj" />
  </ItemGroup>
  
  <!-- Service References -->
  <ItemGroup>
    <WCFMetadata Include="Service References\" />
  </ItemGroup>
  
  <!-- Conditional Package References -->
  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
  </ItemGroup>
</Project>