//
// This code was generated by Visual ReCode 2.0.3.1140
// 
namespace AnnotationService.WcfProxy
{
    public partial class AnnotationSet
    {
        public Structure[] Structures { get; set; }
        public Location[] Locations { get; set; }
    }
}

