//
// This code was generated by Visual ReCode 2.0.3.1140
//

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AnnotationService.WcfProxy
{
    [System.ServiceModel.ServiceContract]
    public interface IAnnotateLocations
    {
        [System.ServiceModel.OperationContract]
        Task<Location> CreateLocation(Location obj, long[] LinkedIDs);

        [System.ServiceModel.OperationContract]
        Task<Location> GetLocationByID(long ID);

        [System.ServiceModel.OperationContract]
        Task<Location[]> GetLocationsByID(long[] IDs);

        [System.ServiceModel.OperationContract]
        Task<Location> GetLastModifiedLocation();

        [System.ServiceModel.OperationContract]
        Task<long[]> GetLinkedLocations(long ID);

        [System.ServiceModel.OperationContract]
        Task<Location[]> GetLocationsForSection(long section, long QueryExecutedTime);

        [System.ServiceModel.OperationContract]
        Task<Location[]> GetLocationsForStructure(long structureID);

        [System.ServiceModel.OperationContract]
        Task<Location[]> GetLocationChangesInMosaicRegion(long section, BoundingRectangle bbox, double MinRadius, long? ModifiedAfterThisUtcTime, long QueryExecutedTime, long[] DeletedIDs);

        [System.ServiceModel.OperationContract]
        Task<AnnotationSet> GetAnnotationsInMosaicRegion(long section, BoundingRectangle bbox, double MinRadius, long? ModifiedAfterThisUtcTime, long QueryExecutedTime, long[] DeletedIDs);

        [System.ServiceModel.OperationContract]
        Task<Location[]> GetLocationChanges(long section, long ModifiedAfterThisUtcTime, long QueryExecutedTime, long[] DeletedIDs);

        [System.ServiceModel.OperationContract]
        Task<long[]> Update(Location[] locations);

        [System.ServiceModel.OperationContract]
        Task CreateLocationLink(long SourceID, long TargetID);

        [System.ServiceModel.OperationContract]
        Task DeleteLocationLink(long SourceID, long TargetID);

        [System.ServiceModel.OperationContract]
        Task<LocationLink[]> GetLocationLinksForSection(long section, long ModifiedAfterThisTime, long QueryExecutedTime, LocationLink[] DeletedLinks);

        [System.ServiceModel.OperationContract]
        Task<LocationLink[]> GetLocationLinksForSectionInMosaicRegion(long section, BoundingRectangle bbox, double MinRadius, long ModifiedAfterThisUtcTime, long QueryExecutedTime, LocationLink[] DeletedLinks);

        [System.ServiceModel.OperationContract]
        Task<LocationHistory[]> GetLocationChangeLog(long? structure_id, DateTime? begin_time, DateTime? end_time);

    }
}

