//
// This code was generated by Visual ReCode 2.0.3.1140
//

using System;
using System.Collections.Generic;

namespace AnnotationService.WcfProxy
{
    public partial class Structure
    {
        public long TypeID { get; set; }
        public string Notes { get; set; }
        public bool Verified { get; set; }
        public string AttributesXml { get; set; }
        public double Confidence { get; set; }
        public StructureLink[] Links { get; set; }
        public long[] ChildIDs { get; set; }
        public string Label { get; set; }
        public string Username { get; set; }
    }
}

