USE [master]
GO

/****** Object:  Database [XXXXXX]    Script Date: 04/06/2010 11:11:15 ******/
CREATE DATABASE [XXXXXX] ON  PRIMARY 
( NAME = N'XXXXXX', FILENAME = N'C:\Database\XXXXXX\XXXXXX.mdf' , SIZE = 165888KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'XXXXXX_log', FILENAME = N'C:\Database\XXXXXX\XXXXXX_log.ldf' , SIZE = 92864KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [XXXXXX] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [XXXXXX].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [XXXXXX] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [XXXXXX] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [XXXXXX] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [XXXXXX] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [XXXXXX] SET ARITHABORT OFF 
GO

ALTER DATABASE [XXXXXX] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [XXXXXX] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [XXXXXX] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [XXXXXX] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [XXXXXX] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [XXXXXX] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [XXXXXX] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [XXXXXX] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [XXXXXX] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [XXXXXX] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [XXXXXX] SET  DISABLE_BROKER 
GO

ALTER DATABASE [XXXXXX] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [XXXXXX] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [XXXXXX] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [XXXXXX] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [XXXXXX] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [XXXXXX] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [XXXXXX] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [XXXXXX] SET  READ_WRITE 
GO

ALTER DATABASE [XXXXXX] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [XXXXXX] SET  MULTI_USER 
GO

ALTER DATABASE [XXXXXX] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [XXXXXX] SET DB_CHAINING OFF 
GO


