-- Enable Query Store on your database
ALTER DATABASE NeitzInferiorMonkey SET QUERY_STORE = ON;
ALTER DATABASE NeitzInferiorMonkey SET QUERY_STORE (
    OPERATION_MODE = READ_WRITE,
    CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30),
    DATA_FLUSH_INTERVAL_SECONDS = 3000,
    MAX_STORAGE_SIZE_MB = 1000,
    INTERVAL_LENGTH_MINUTES = 10
);