<?xml version="1.0" encoding="utf-8"?><Database Name="Rabbit" Class="AnnotationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=OpR-Marc-RC1\SQLEXPRESS;Initial Catalog=Rabbit;Integrated Security=True" SettingsObjectName="AnnotationDatabase.Properties.Settings" SettingsPropertyName="RabbitConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.StructureType" Member="DBStructureTypes">
    <Type Name="DBStructureType">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentID" Storage="_Parent" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="MarkupType" Type="System.String" DbType="NChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Tags" Type="System.String" DbType="Xml" CanBeNull="true" />
      <Column Name="StructureTags" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="Abstract" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" UpdateCheck="Always" IsVersion="true" />
      <Column Name="Code" Type="System.String" DbType="NChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="HotKey" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NChar NOT NULL" CanBeNull="false" IsDelayLoaded="true" />
      <Column Name="LastModified" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsReadOnly="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Created" AutoSync="OnInsert" Type="System.DateTime" DbType="DateTime NOT NULL" IsReadOnly="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="DBStructureType_DBStructureType" Member="Children" Storage="_dbStructureTypes" ThisKey="ID" OtherKey="ParentID" Type="DBStructureType" />
      <Association Name="DBStructureType_StructureTemplate" Member="StructureTemplates" ThisKey="ID" OtherKey="StructureTypeID" Type="StructureTemplate" />
      <Association Name="DBStructureType_DBStructure" Member="Structures" Storage="_DBStructures" ThisKey="ID" OtherKey="TypeID" Type="DBStructure" />
      <Association Name="DBStructureType_DBStructureType" Member="Parent" Storage="_StructureType1" ThisKey="ParentID" OtherKey="ID" Type="DBStructureType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Location" Member="DBLocations">
    <Type Name="DBLocation" Id="ID2">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="ParentID" Type="System.Int64" DbType="BigInt" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="X" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="Y" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="Z" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="Verticies" Type="System.Data.Linq.Binary" DbType="VarBinary(64)" CanBeNull="true" UpdateCheck="WhenChanged" />
      <Column Name="Closed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" UpdateCheck="Always" IsVersion="true" />
      <Column Name="Tags" Type="System.String" DbType="Xml" CanBeNull="true" UpdateCheck="WhenChanged" />
      <Column Name="VolumeX" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="VolumeY" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="Terminal" Storage="_Extensible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="OffEdge" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="Radius" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="TypeCode" Type="System.Int16" DbType="smallint NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="LastModified" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsReadOnly="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NChar NOT NULL" CanBeNull="false" />
      <Column Name="Created" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsReadOnly="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="DBLocation_DBLocationLink" Member="IsLinkedTo" Storage="_SourcedBy" ThisKey="ID" OtherKey="LinkedFrom" Type="DBLocationLink" />
      <Association Name="DBLocation_DBLocationLink1" Member="IsLinkedFrom" Storage="_TargettedBy" ThisKey="ID" OtherKey="LinkedTo" Type="DBLocationLink" />
      <Association Name="DBStructure_DBLocation" Member="DBStructure" ThisKey="ParentID" OtherKey="ID" Type="DBStructure" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LocationLink" Member="DBLocationLinks">
    <Type Name="DBLocationLink" Id="ID1">
      <Column Name="A" Member="LinkedFrom" Storage="_Source" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="B" Member="LinkedTo" Storage="_Target" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NChar NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Created" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsReadOnly="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="DBLocation_DBLocationLink" Member="SourceLocation" ThisKey="LinkedFrom" OtherKey="ID" Type="DBLocation" IsForeignKey="true" />
      <Association Name="DBLocation_DBLocationLink1" Member="TargetLocation" ThisKey="LinkedTo" OtherKey="ID" Type="DBLocation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StructureTemplates" Member="StructureTemplates">
    <Type Name="StructureTemplate">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="Name" Type="System.String" DbType="Char(64) NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="StructureTypeID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="StructureTags" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" UpdateCheck="Always" IsVersion="true" />
      <Association Name="DBStructureType_StructureTemplate" Member="DBStructureType" ThisKey="StructureTypeID" OtherKey="ID" Type="DBStructureType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StructureLink" Member="DBStructureLinks">
    <Type Name="DBStructureLink">
      <Column Name="SourceID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TargetID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Bidirectional" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Tags" Type="System.String" DbType="Xml" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="Username" Type="System.String" DbType="NChar NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="Created" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsReadOnly="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LastModified" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsReadOnly="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="DBStructure_DBStructureLink" Member="SourceStructure" Storage="_Structure" ThisKey="SourceID" OtherKey="ID" Type="DBStructure" IsForeignKey="true" />
      <Association Name="DBStructure_DBStructureLink1" Member="TargetStructure" Storage="_DBStructure" ThisKey="TargetID" OtherKey="ID" Type="DBStructure" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Structure" Member="DBStructures">
    <Type Name="DBStructure">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="TypeID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="Notes" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="WhenChanged" />
      <Column Name="Verified" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="Tags" Type="System.String" DbType="Xml" CanBeNull="true" UpdateCheck="WhenChanged" />
      <Column Name="Confidence" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" UpdateCheck="Always" IsVersion="true" />
      <Column Name="ParentID" Type="System.Int64" DbType="BigInt" CanBeNull="true" UpdateCheck="WhenChanged" />
      <Column Name="Label" Type="System.String" DbType="Varchar(32)" CanBeNull="true" UpdateCheck="WhenChanged" />
      <Column Name="Username" Type="System.String" DbType="NChar NOT NULL" CanBeNull="false" UpdateCheck="WhenChanged" />
      <Column Name="LastModified" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsReadOnly="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Created" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsReadOnly="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="DBStructure_DBLocation" Member="DBLocations" ThisKey="ID" OtherKey="ParentID" Type="DBLocation" />
      <Association Name="DBStructure_DBStructureLink" Member="IsSourceOf" Storage="_DBStructureLinks" ThisKey="ID" OtherKey="SourceID" Type="DBStructureLink" />
      <Association Name="DBStructure_DBStructureLink1" Member="IsTargetOf" Storage="_DBStructureLinks1" ThisKey="ID" OtherKey="TargetID" Type="DBStructureLink" />
      <Association Name="DBStructure_DBStructure" Member="ChildStructures" Storage="_DBStructures" ThisKey="ID" OtherKey="ParentID" Type="DBStructure" />
      <Association Name="DBStructureType_DBStructure" Member="StructureType" Storage="_DBStructureType" ThisKey="TypeID" OtherKey="ID" Type="DBStructureType" IsForeignKey="true" />
      <Association Name="DBStructure_DBStructure" Member="ParentStructure" ThisKey="ParentID" OtherKey="ID" Type="DBStructure" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeletedLocations" Member="DBDeletedLocations">
    <Type Name="DBDeletedLocations">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DeletedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.MergeStructures" Method="MergeStructures">
    <Parameter Name="KeepStructureID" Parameter="keepStructureID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="MergeStructureID" Parameter="mergeStructureID" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SelectSectionLocationLinks" Method="SelectSectionLocationLinks">
    <Parameter Name="Z" Parameter="z" Type="System.Double" DbType="Float" />
    <Parameter Name="QueryDate" Parameter="queryDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.ApproximateStructureLocations" Method="ApproximateStructureLocations">
    <ElementType Name="ApproximateStructureLocationsResult">
      <Column Name="ParentID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="X" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Y" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Z" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Radius" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectLastModifiedLocationByUsers" Method="SelectLastModifiedLocationByUsers">
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.ApproximateStructureLocation" Method="ApproximateStructureLocation">
    <Parameter Name="StructureID" Parameter="structureID" Type="System.Int32" DbType="Int" />
    <ElementType Name="ApproximateStructureLocationResult1">
      <Column Name="X" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Y" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Z" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Radius" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectNumConnectionsPerStructure" Method="SelectNumConnectionsPerStructure">
    <ElementType Name="SelectNumConnectionsPerStructureResult">
      <Column Name="StructureID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Label" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
      <Column Name="NumConnections" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectStructureLabels" Method="SelectStructureLabels">
    <ElementType Name="SelectStructureLabelsResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="VarChar(64)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CountChildStructuresByType" Method="CountChildStructuresByType">
    <Parameter Name="StructureID" Parameter="structureID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="CountChildStructuresByTypeResult">
      <Column Name="TypeID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectUnfinishedStructureBranches" Method="SelectUnfinishedStructureBranches">
    <Parameter Name="StructureID" Parameter="structureID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="SelectUnfinishedStructureBranchesResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SelectUnfinishedStructureBranchesWithPosition" Method="SelectUnfinishedStructureBranchesWithPosition">
    <Parameter Name="StructureID" Parameter="structureID" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="SelectUnfinishedStructureBranchesWithPositionResult">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="X" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Y" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Z" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Radius" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>