<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
	<LangVersion>latest</LangVersion>
    <AssemblyName>ODataClient</AssemblyName>
    <RootNamespace>ODataClient</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.OData.Client" Version="7.12.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.ComponentModel.DataAnnotations" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ODataClient.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>ODataClient.cs</LastGenOutput>
    </Content>
    <None Include="App.config" />
    <None Include="ODataClient.ttinclude" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349B6-6B84-4DF5-91F0-309BEEBAD82D}" />
  </ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="Generated/OData ServiceCsdl.xml" />
	</ItemGroup>

</Project>