//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectomeODataV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StructureType_CT
    {
        public byte[] C___start_lsn { get; set; }
        public byte[] C___end_lsn { get; set; }
        public byte[] C___seqval { get; set; }
        public int C___operation { get; set; }
        public byte[] C___update_mask { get; set; }
        public Nullable<long> ID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public string MarkupType { get; set; }
        public string Tags { get; set; }
        public string StructureTags { get; set; }
        public Nullable<bool> Abstract { get; set; }
        public Nullable<int> Color { get; set; }
        public byte[] Version { get; set; }
        public string Code { get; set; }
        public string HotKey { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
