<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
	  <PackageReference Include="Simple.OData.V4.Client" Version="6.0.1" />
      <PackageReference Include="EntityFramework" Version="6.5.1" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
		<PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
		<PackageReference Include="System.Memory" Version="4.6.3" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0' or '$(TargetFramework)' == 'netstandard2.0'">
		<PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Geometry\Geometry.csproj" />
    <ProjectReference Include="..\AnnotationServiceTypes\AnnotationServiceTypes.WCF.csproj" />
    <ProjectReference Include="..\SqlGeometryAnnotationExtensions\SqlGeometryAnnotationExtensions.csproj" />
    <ProjectReference Include="..\SqlGeometryUtils\SqlGeometryUtils.csproj" />
    <ProjectReference Include="..\AnnotationVizLib\AnnotationVizLib.csproj" />
  </ItemGroup>
</Project>