<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>RuneWpfControlLibrary</RootNamespace>
    <AssemblyName>RuneWpfControlLibrary</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Page Include="GoToLocationForm.xaml">
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
</Project>