<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>MIConvexHullExtensions</AssemblyName>
    <RootNamespace>MIConvexHullExtensions</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MIConvexHull" Version="1.1.19.1019" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Geometry\Geometry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="app.config" />
  </ItemGroup>

</Project>
